### ISSUE TITLE
exceptions.OSError: [Errno 20] Not a directory: '/tmp/mvd-r39-develop-j0ylm_.egg/mvd'

### ISSUE THREAD

**Issue by leonGTHB** [scrapy/scrapyd#118]
my scrapy.cfg setting :
[deploy]
url = http://172.16.0.210:6800/
project = mvd
username = deploy

I  google a lot and there isn't an right answer . Have any ideas?

**Comment by leonGTHB** [comment]
A detail log:


2015-11-27 11:05:03+0800 [-] "172.16.0.62" - - [27/Nov/2015:03:05:02 +0000] "POST /schedule.json HTTP/1.1" 200 62 "-" "curl/7.43.0"
2015-11-27 11:05:05+0800 [-] Process started:  project='mvd' spider='airbnb' job='a735187294b311e5ab5a0000ac1000d2' pid=1924 log='/var/log/scrapyd/mvd/airbnb/a735187294b311e5ab5a0000ac1000d2.log' items='/mnt/spider/scrapyd/items/mvd/airbnb/a735187294b311e5ab5a0000ac1000d2.jl'
2015-11-27 11:05:06+0800 [Launcher,1924/stderr] Unhandled error in Deferred:
2015-11-27 11:05:06+0800 [Launcher,1924/stderr]

        Traceback (most recent call last):
          File "/usr/local/lib/python2.7/dist-packages/scrapy/cmdline.py", line 150, in _run_command
            cmd.run(args, opts)
          File "/usr/local/lib/python2.7/dist-packages/scrapy/commands/crawl.py", line 57, in run
            self.crawler_process.crawl(spname, **opts.spargs)
          File "/usr/local/lib/python2.7/dist-packages/scrapy/crawler.py", line 153, in crawl
            d = crawler.crawl(*args, **kwargs)
          File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 1274, in unwindGenerator
            return _inlineCallbacks(None, gen, Deferred())
        --- <exception caught here> ---
          File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 1128, in _inlineCallbacks
            result = g.send(result)
          File "/usr/local/lib/python2.7/dist-packages/scrapy/crawler.py", line 71, in crawl
            self.engine = self._create_engine()
          File "/usr/local/lib/python2.7/dist-packages/scrapy/crawler.py", line 83, in _create_engine
            return ExecutionEngine(self, lambda _: self.stop())
          File "/usr/local/lib/python2.7/dist-packages/scrapy/core/engine.py", line 67, in __init__
            self.scraper = Scraper(crawler)
          File "/usr/local/lib/python2.7/dist-packages/scrapy/core/scraper.py", line 70, in __init__
            self.itemproc = itemproc_cls.from_crawler(crawler)
          File "/usr/local/lib/python2.7/dist-packages/scrapy/middleware.py", line 56, in from_crawler
            return cls.from_settings(crawler.settings, crawler)
          File "/usr/local/lib/python2.7/dist-packages/scrapy/middleware.py", line 34, in from_settings
            mw = mwcls.from_crawler(crawler)
          File "/usr/local/lib/python2.7/dist-packages/scrapy/pipelines/media.py", line 33, in from_crawler
            pipe = cls.from_settings(crawler.settings)
          File "/usr/local/lib/python2.7/dist-packages/scrapy/pipelines/images.py", line 57, in from_settings
            return cls(store_uri)
          File "build/bdist.macosx-10.11-x86_64/egg/mvd/pipelines.py", line 32, in __init__

          File "/usr/local/lib/python2.7/dist-packages/scrapy/pipelines/files.py", line 160, in __init__
            self.store = self._get_store(store_uri)
          File "/usr/local/lib/python2.7/dist-packages/scrapy/pipelines/files.py", line 181, in _get_store
            return store_cls(uri)
          File "/usr/local/lib/python2.7/dist-packages/scrapy/pipelines/files.py", line 43, in __init__
            self._mkdir(self.basedir)
          File "/usr/local/lib/python2.7/dist-packages/scrapy/pipelines/files.py", line 72, in _mkdir
            os.makedirs(dirname)
          File "/usr/lib/python2.7/os.py", line 150, in makedirs
            makedirs(head, mode)
          File "/usr/lib/python2.7/os.py", line 150, in makedirs
            makedirs(head, mode)
          File "/usr/lib/python2.7/os.py", line 157, in makedirs
            mkdir(name, mode)
        exceptions.OSError: [Errno 20] Not a directory: '/tmp/mvd-r39-develop-j0ylm_.egg/mvd'
2015-11-27 11:05:06+0800 [-] Process finished:  project='mvd' spider='airbnb' job='a735187294b311e5ab5a0000ac1000d2' pid=1924 log='/var/log/scrapyd/mvd/airbnb/a735187294b311e5ab5a0000ac1000d2.log' items='/mnt/spider/scrapyd/items/mvd/airbnb/a735187294b311e5ab5a0000ac1000d2.jl'

**Comment by jackie2013** [comment]
yes, I get the same problem.

**Comment by Digenis** [comment]
You can't use `__path__` in code packaged in an egg.

Sometimes what you want is pkg_resources
https://pythonhosted.org/setuptools/pkg_resources.html#id23
but in your case you need something different.
Read about the scrapy setting called `PROJECT_DATA_DIR`
