### ISSUE TITLE
sqlite3.OperationalError: unable to open database file

### ISSUE THREAD

**Issue by AlexIzydorczyk** [scrapy/scrapyd#128]
Hi all,

I'm receiving the following error when attempting to add a project (or in some cases just start scrapyd):

```
Unhandled Error
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/twisted/application/app.py", line 617, in run

  File "/usr/local/lib/python2.7/dist-packages/twisted/scripts/twistd.py", line 25, in runApp

  File "/usr/local/lib/python2.7/dist-packages/twisted/application/app.py", line 348, in run

  File "/usr/local/lib/python2.7/dist-packages/twisted/application/app.py", line 413, in createOrGetApplication

--- <exception caught here> ---
  File "/usr/local/lib/python2.7/dist-packages/twisted/application/app.py", line 424, in getApplication

  File "/usr/local/lib/python2.7/dist-packages/twisted/application/service.py", line 411, in loadApplication

  File "/usr/local/lib/python2.7/dist-packages/twisted/persisted/sob.py", line 224, in loadValueFromFile

  File "/usr/local/lib/python2.7/dist-packages/scrapyd/txapp.py", line 3, in <module>

  File "/usr/local/lib/python2.7/dist-packages/scrapyd/__init__.py", line 14, in get_application
    return appfunc(config)
  File "/usr/local/lib/python2.7/dist-packages/scrapyd/app.py", line 37, in application

  File "/usr/local/lib/python2.7/dist-packages/scrapyd/website.py", line 35, in __init__

  File "/usr/local/lib/python2.7/dist-packages/scrapyd/website.py", line 38, in update_projects

  File "/usr/local/lib/python2.7/dist-packages/scrapyd/poller.py", line 30, in update_projects

  File "/usr/local/lib/python2.7/dist-packages/scrapyd/utils.py", line 61, in get_spider_queues

  File "/usr/local/lib/python2.7/dist-packages/scrapyd/spiderqueue.py", line 12, in __init__

  File "/usr/local/lib/python2.7/dist-packages/scrapyd/sqlite.py", line 95, in __init__

sqlite3.OperationalError: unable to open database file
```

Typically, this would suggest a permissions error in the dbs folder (`/var/lib/scrapyd/dbs`). However, I've checked permissions on that folder/files, have tried granting all users permissions to those files, and running scrapyd as root. 

Could there be anything deeper going on here? / What other checks/diagnostics might help identify the problem?

I've tried running scrapyd in debug mode, and can confirm that sqlite3.connect() fails when trying to connect to self.database in the sqlite.py script. 

I should note that there are 300+ projects, all with multiple versions, deployed on my scrapyd server. Scrapyd was working fine until recently - it's strange because no system settings were really changed on the server. 

Any pointers to help track down this issue would be greatly appreciated. 

Thanks,
Alex

**Comment by jdemaeyer** [comment]
Hey Alex,

I know this is a desparate shot, but any chance that the hard drive (or the partition on which `/var/lib/scrapyd/dbs` lives, anyways) is full?

**Comment by AlexIzydorczyk** [comment]
Hi Jakob, really appreciate the response!

Just ran - unfortunately, that doesn't seem to be the problem - only 14% used.

I've tried identifying the issue by running through the debugger. If I step through the deploy process, the exception occurs in the initialization of the SqlitePriorityQueue:
```
    def __init__(self, database=None, table="queue"):
        self.database = database or ':memory:'
        self.table = table
        # about check_same_thread: http://twistedmatrix.com/trac/ticket/4040
        self.conn = sqlite3.connect(self.database, check_same_thread=False)
        q = "create table if not exists %s (id integer primary key, " \
            "priority real key, message blob)" % table
        self.conn.execute(q)
```

If I step in, I can see that self.database is one of my projects' db path (it changes - but something like /var/lib/scrapyd/dbs/someproject.db) - so this is being called from the get_spider_list() utils method, I believe? 

What's very strange is that at that point, if I run sqlite3.connect("anything") in the debugger at that exception breakpoint - even when having started scrapyd as root and accessing a directory with completely open permissions - sqlite3 fails with the same error `*** sqlite3.OperationalError: unable to open database file`

To add to the confusion, this error seems sporadic and hard to reproduce. If it occurs and I delete the project egg file that was just deployed and restart scrapyd, I can upload a different project and it seems to work just fine. Further, we have 4 users deploying projects from different machines. One user has this failure occur every time while it is more project specific for others.

Finally, if I delete all the egg files - everyone seems to be able to deploy anything successfully (at least for the first few projects).  


The only way I've found to avoid the error entirely is if I connect to an in memory database.

I can seemingly fix the issue by forcing scrapyd to exclusively use ':memory:', although I think other parts of the code don't actually handle this case (jobs won't schedule for instance, probably because the scheduler expects a separate .db file for each project). Is this correct?

**Comment by jdemaeyer** [comment]
Hey Alex,

thanks for all the additional info. Can you check some additional things?
* Just to be sure, even if the disk drive is not full, maybe the user has exceeded his quota?
* What version of `scrapyd` is running on the server (and on top of which Python version)?
* Are the clients using different versions of `scrapyd-client` (particularly the one that ​always​ gets failures)?
* Could you paste your config file, or parts of it, if it's not too sensible?
* Are you using relative instead of absolute paths somewhere?
* At the exception breakpoint, could you print the working directory? Do you also get an exception if you try to establish a sqlite3 connection using a full path somewhere in the home directory?
* Are there any non-ascii characters in your project names?

Cheers,
-Jakob

**Comment by Digenis** [comment]
Project names can conflict without warnings.

* Are there any forward/backward slashes in your project names?
* Is your database folder mounted on a case-insensitive filesystem?

Here's an interesting fact:
If 2 different project names happen both to be pointing to the scrapyd user's home directory relatively from `/tmp`, they will both be known as '~'

See http://www.spect.cl/blog/2015/11/security-audit-scrapyd/#1projectnameandeggstorageissues
and #117

**Comment by Digenis** [comment]
closing due to inactivity
