### ISSUE TITLE
utils.get_spider_list() discards traceback on failure

### ISSUE THREAD

**Issue by Aireed** [scrapy/scrapyd#129]
```
2016-03-07 16:06:45+0800 [HTTPChannel,19,99.48.58.82] 99.48.58.82 - - [07/Mar/2016:08:06:44 +0000] "POST /addversion.json HTTP/1.1" 200 123 "-" "Python-urllib/2.7"
^C2016-03-07 16:24:20+0800 [-] Received SIGINT, shutting down.
2016-03-07 16:24:20+0800 [-] (TCP Port 6800 Closed)
2016-03-07 16:24:20+0800 [-] Stopping factory <twisted.web.server.Site instance at 0x7fbd7c3f47e8>
2016-03-07 16:24:20+0800 [-] Main loop terminated.
2016-03-07 16:24:20+0800 [-] Server Shut Down.
root@redis-1:/etc# sudo scrapyd
2016-03-07 16:24:22+0800 [-] Log opened.
2016-03-07 16:24:22+0800 [-] twistd 13.2.0 (/usr/bin/python 2.7.6) starting up.
2016-03-07 16:24:22+0800 [-] reactor class: twisted.internet.epollreactor.EPollReactor.
2016-03-07 16:24:22+0800 [-] Site starting on 6800
2016-03-07 16:24:22+0800 [-] Starting factory <twisted.web.server.Site instance at 0x7fd65ce26bd8>
2016-03-07 16:24:22+0800 [Launcher] Scrapyd 1.1.0 started: max_proc=4, runner='scrapyd.runner'
2016-03-07 16:24:41+0800 [HTTPChannel,0,99.48.58.82] Unhandled Error
        Traceback (most recent call last):
          File "/usr/lib/python2.7/dist-packages/twisted/web/http.py", line 1730, in allContentReceived
            req.requestReceived(command, path, version)
          File "/usr/lib/python2.7/dist-packages/twisted/web/http.py", line 826, in requestReceived
            self.process()
          File "/usr/lib/python2.7/dist-packages/twisted/web/server.py", line 189, in process
            self.render(resrc)
          File "/usr/lib/python2.7/dist-packages/twisted/web/server.py", line 238, in render
            body = resrc.render(self)
        --- <exception caught here> ---
          File "/usr/local/lib/python2.7/dist-packages/scrapyd-1.1.0-py2.7.egg/scrapyd/webservice.py", line 17, in render
            return JsonResource.render(self, txrequest)
          File "/usr/local/lib/python2.7/dist-packages/scrapyd-1.1.0-py2.7.egg/scrapyd/utils.py", line 19, in render
            r = resource.Resource.render(self, txrequest)
          File "/usr/lib/python2.7/dist-packages/twisted/web/resource.py", line 250, in render
            return m(request)
          File "/usr/local/lib/python2.7/dist-packages/scrapyd-1.1.0-py2.7.egg/scrapyd/webservice.py", line 86, in render_POST
            spiders = get_spider_list(project, version=version)
          File "/usr/local/lib/python2.7/dist-packages/scrapyd-1.1.0-py2.7.egg/scrapyd/utils.py", line 116, in get_spider_list
            raise RuntimeError(msg.splitlines()[-1])
        exceptions.RuntimeError: AttributeError: 'NoneType' object has no attribute 'module_name'

2016-03-07 16:24:41+0800 [HTTPChannel,0,99.48.58.82] 99.48.58.82 - - [07/Mar/2016:08:24:41 +0000] "POST /addversion.json HTTP/1.1" 200 123 "-" "Python-urllib/2.7"
```

My Client shows the info like:
E:\code\scrapy-project\firstscrapy>python  scrapyd-deploy  firstscrapy -p First
Packing version 1457339121
Deploying to project "First" in http://99.48.58.210:6800/addversion.json
Server response (200):
{"status": "error", "message": "AttributeError: 'NoneType' object has no attribute 'module_name'", "node_name": "redis-1"}

**Comment by Digenis** [comment]
I guess you have some problem in you scrapy project,
something that makes it break in the environment of your scrapyd.

Scrapyd is also responsible that you didn't realize it.
`raise RuntimeError(msg.splitlines()[-1])` strips the whole traceback
and you can't know where/how the exception occurred.
This will be fixed on a later version.

If in scrapyd's source you replace the line
`raise RuntimeError(msg.splitlines()[-1])`
with `raise RuntimeError(msg)`
you will see the whole traceback
and find what's wrong in your project.

**Comment by Aireed** [comment]
@Digenis 3ks.It looks like scrapyd can't find the settings file.
it's likely that i failed to package the project to the server for some errors in my project.

Traceback (most recent call last):
          File "/usr/lib/python2.7/dist-packages/twisted/web/http.py", line 1730, in allContentReceived
            req.requestReceived(command, path, version)
          File "/usr/lib/python2.7/dist-packages/twisted/web/http.py", line 826, in requestReceived
            self.process()
          File "/usr/lib/python2.7/dist-packages/twisted/web/server.py", line 189, in process
            self.render(resrc)
          File "/usr/lib/python2.7/dist-packages/twisted/web/server.py", line 238, in render
            body = resrc.render(self)
        --- <exception caught here> ---
          File "/usr/local/lib/python2.7/dist-packages/scrapyd-1.1.0-py2.7.egg/scrapyd/webservice.py", line 17, in render
            return JsonResource.render(self, txrequest)
          File "/usr/local/lib/python2.7/dist-packages/scrapyd-1.1.0-py2.7.egg/scrapyd/utils.py", line 19, in render
            r = resource.Resource.render(self, txrequest)
          File "/usr/lib/python2.7/dist-packages/twisted/web/resource.py", line 250, in render
            return m(request)
          File "/usr/local/lib/python2.7/dist-packages/scrapyd-1.1.0-py2.7.egg/scrapyd/webservice.py", line 51, in render_POST
            spiders = get_spider_list(project, version=version)
          File "/usr/local/lib/python2.7/dist-packages/scrapyd-1.1.0-py2.7.egg/scrapyd/utils.py", line 117, in get_spider_list
            raise RuntimeError(msg)
        exceptions.RuntimeError: Traceback (most recent call last):
          File "/usr/lib/python2.7/runpy.py", line 162, in _run_module_as_main
            "__main__", fname, loader, pkg_name)
          File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
            exec code in run_globals
          File "/usr/local/lib/python2.7/dist-packages/scrapyd-1.1.0-py2.7.egg/scrapyd/runner.py", line 40, in <module>
            main()
          File "/usr/local/lib/python2.7/dist-packages/scrapyd-1.1.0-py2.7.egg/scrapyd/runner.py", line 35, in main
            with project_environment(project):
          File "/usr/lib/python2.7/contextlib.py", line 17, in __enter__
            return self.gen.next()
          File "/usr/local/lib/python2.7/dist-packages/scrapyd-1.1.0-py2.7.egg/scrapyd/runner.py", line 23, in project_environment
            activate_egg(eggpath)
          File "/usr/local/lib/python2.7/dist-packages/scrapyd-1.1.0-py2.7.egg/scrapyd/eggutils.py", line 13, in activate_egg
            settings_module = d.get_entry_info('scrapy', 'settings').module_name
        AttributeError: 'NoneType' object has no attribute 'module_name'

**Comment by Digenis** [comment]
Maybe you renamed/moved your project's folder.
Delete your setup.py
and check if setup.cfg names the project and the settings module directly.
For more support ask in the [scrapy-users](https://groups.google.com/d/forum/scrapy-users) mailing list

**Comment by longfly04** [comment]
I can not follow...

**Comment by Aireed** [comment]
@Digenis 3ks.

**Comment by Digenis** [comment]
There's a part of this issue that requires fixing scrapyd so I reopen this.
