### ISSUE TITLE
Can't deploy scrapy to scrapyd server

### ISSUE THREAD

**Issue by artyomboyko** [scrapy/scrapyd#145]
I'm trying to deploy spider created via [Portia](https://portia.readthedocs.io/en/latest/projects.html#deployment). Portia, scrapyd - all is latest versions.

I'm running **scrapyd** server just by command:

```
scrapyd
```

I'm getting this result on my machine locally:

```
$> cd PROJECT_PATH_HERE;
$> scrapyd-deploy
Packing version 1463420166
Deploying to project "retail" in http://X.X.X.X:6800/addversion.json
Server response (200):
{"status": "error", "message": "AttributeError: 'list' object has no attribute 'iteritems'", "node_name": "vaua0048313.online-vm.com"}
```

On the server side (**Ubuntu 12.04.5 LTS**):

```
root@server:~# scrapyd
2016-05-16 17:35:42+0000 [-] Log opened.
2016-05-16 17:35:42+0000 [-] twistd 16.1.1 (/usr/bin/python 2.7.3) starting up.
2016-05-16 17:35:42+0000 [-] reactor class: twisted.internet.epollreactor.EPollReactor.
2016-05-16 17:35:42+0000 [-] Site starting on 6800
2016-05-16 17:35:42+0000 [-] Starting factory <twisted.web.server.Site instance at 0x2f5d950>
2016-05-16 17:35:42+0000 [Launcher] Scrapyd 1.1.0 started: max_proc=12, runner='scrapyd.runner'
2016-05-16 17:36:06+0000 [_GenericHTTPChannelProtocol,0,78.111.181.96] Unhandled Error
        Traceback (most recent call last):
          File "/usr/local/lib/python2.7/dist-packages/twisted/web/http.py", line 1767, in allContentReceived
            req.requestReceived(command, path, version)
          File "/usr/local/lib/python2.7/dist-packages/twisted/web/http.py", line 768, in requestReceived
            self.process()
          File "/usr/local/lib/python2.7/dist-packages/twisted/web/server.py", line 183, in process
            self.render(resrc)
          File "/usr/local/lib/python2.7/dist-packages/twisted/web/server.py", line 234, in render
            body = resrc.render(self)
        --- <exception caught here> ---
          File "/usr/local/lib/python2.7/dist-packages/scrapyd/webservice.py", line 17, in render
            return JsonResource.render(self, txrequest)
          File "/usr/local/lib/python2.7/dist-packages/scrapyd/utils.py", line 19, in render
            r = resource.Resource.render(self, txrequest)
          File "/usr/local/lib/python2.7/dist-packages/twisted/web/resource.py", line 250, in render
            return m(request)
          File "/usr/local/lib/python2.7/dist-packages/scrapyd/webservice.py", line 79, in render_POST
            spiders = get_spider_list(project, version=version)
          File "/usr/local/lib/python2.7/dist-packages/scrapyd/utils.py", line 116, in get_spider_list
            raise RuntimeError(msg.splitlines()[-1])
        exceptions.RuntimeError: AttributeError: 'list' object has no attribute 'iteritems'

2016-05-16 17:36:06+0000 [-] "78.111.181.96" - - [16/May/2016:17:36:05 +0000] "POST /addversion.json HTTP/1.1" 200 135 "-" "Python-urllib/2.7"
```

What am I doing wrong ?

**Comment by Digenis** [comment]
Does the command `scrapy list` work inside your project dir?

**Comment by artyomboyko** [comment]
```
vagrant@portia:/vagrant/slyd/slyd/data/projects/retail$ scrapy list
/usr/local/lib/python2.7/dist-packages/scrapy/crawler.py:115: ScrapyDeprecationWarning: SPIDER_MANAGER_CLASS option is deprecated. Please use SPIDER_LOADER_CLASS.
  self.spider_loader = _get_spider_loader(settings)
Traceback (most recent call last):
  File "/usr/local/bin/scrapy", line 11, in <module>
    sys.exit(execute())
  File "/usr/local/lib/python2.7/dist-packages/scrapy/cmdline.py", line 142, in execute
    cmd.crawler_process = CrawlerProcess(settings)
  File "/usr/local/lib/python2.7/dist-packages/scrapy/crawler.py", line 209, in __init__
    super(CrawlerProcess, self).__init__(settings)
  File "/usr/local/lib/python2.7/dist-packages/scrapy/crawler.py", line 115, in __init__
    self.spider_loader = _get_spider_loader(settings)
  File "/usr/local/lib/python2.7/dist-packages/scrapy/crawler.py", line 296, in _get_spider_loader
    return loader_cls.from_settings(settings.frozencopy())
  File "/vagrant/slybot/slybot/spidermanager.py", line 40, in from_settings
    return cls(datadir, spider_cls, settings=settings)
  File "/vagrant/slybot/slybot/spidermanager.py", line 25, in __init__
    self._specs = open_project_from_dir(datadir)
  File "/vagrant/slybot/slybot/utils.py", line 31, in open_project_from_dir
    with open(os.path.join(project_dir, "items.json")) as f:
IOError: [Errno 2] No such file or directory: 'slybot-project/items.json'
```

**Comment by Digenis** [comment]
This is a different error from the one you get in scrapyd.
My guess is that this `slybot-projects/items.json`
at some point has a list which you try to treat as a dictionary.

Portia doesn't require scrapyd to work, does it?

**Comment by artyomboyko** [comment]
I simply don't understand it. Is it possible to deploy Portia crawler to scrapyd ? 

I have clean installation of scrapy server. Installed vi pip, all dependencies installed. I'm running it just with `scrapyd` command, no config file.

In Portia side of things I'm creating very simple project. I'm logging in into vagrant ssh, going into project directory and running scrapyd-deploy (with changes in scrapy.cfg). What can I possibly do wrong ?

**Comment by Digenis** [comment]
Please find in your installation directory `scrapy/utils.py`
and replace the line `raise RuntimeError(msg.splitlines()[-1])`
with `raise RuntimeError(msg)`.
Then restart the scrapyd server, deploy your project
and paste the new traceback here.

(this is to workaround a design mistake that makes debugging hard)

**Comment by artyomboyko** [comment]
```
2016-05-19T17:56:54+0000 [_GenericHTTPChannelProtocol,0,78.111.181.96] Unhandled Error
        Traceback (most recent call last):
          File "/usr/local/lib/python2.7/dist-packages/twisted/web/http.py", line 1781, in allContentReceived
            req.requestReceived(command, path, version)
          File "/usr/local/lib/python2.7/dist-packages/twisted/web/http.py", line 768, in requestReceived
            self.process()
          File "/usr/local/lib/python2.7/dist-packages/twisted/web/server.py", line 183, in process
            self.render(resrc)
          File "/usr/local/lib/python2.7/dist-packages/twisted/web/server.py", line 234, in render
            body = resrc.render(self)
        --- <exception caught here> ---
          File "/usr/local/lib/python2.7/dist-packages/scrapyd/webservice.py", line 17, in render
            return JsonResource.render(self, txrequest)
          File "/usr/local/lib/python2.7/dist-packages/scrapyd/utils.py", line 19, in render
            r = resource.Resource.render(self, txrequest)
          File "/usr/local/lib/python2.7/dist-packages/twisted/web/resource.py", line 250, in render
            return m(request)
          File "/usr/local/lib/python2.7/dist-packages/scrapyd/webservice.py", line 79, in render_POST
            spiders = get_spider_list(project, version=version)
          File "/usr/local/lib/python2.7/dist-packages/scrapyd/utils.py", line 116, in get_spider_list
            raise RuntimeError(msg)
        exceptions.RuntimeError: Traceback (most recent call last):
          File "/usr/lib/python2.7/runpy.py", line 162, in _run_module_as_main
            "__main__", fname, loader, pkg_name)
          File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
            exec code in run_globals
          File "/usr/local/lib/python2.7/dist-packages/scrapyd/runner.py", line 40, in <module>
            main()
          File "/usr/local/lib/python2.7/dist-packages/scrapyd/runner.py", line 37, in main
            execute()
          File "/usr/local/lib/python2.7/dist-packages/scrapy/cmdline.py", line 108, in execute
            settings = get_project_settings()
          File "/usr/local/lib/python2.7/dist-packages/scrapy/utils/project.py", line 60, in get_project_settings
            settings.setmodule(settings_module_path, priority='project')
          File "/usr/local/lib/python2.7/dist-packages/scrapy/settings/__init__.py", line 285, in setmodule
            self.set(key, getattr(module, key), priority)
          File "/usr/local/lib/python2.7/dist-packages/scrapy/settings/__init__.py", line 260, in set
            self.attributes[name].set(value, priority)
          File "/usr/local/lib/python2.7/dist-packages/scrapy/settings/__init__.py", line 55, in set
            value = BaseSettings(value, priority=priority)
          File "/usr/local/lib/python2.7/dist-packages/scrapy/settings/__init__.py", line 91, in __init__
            self.update(values, priority)
          File "/usr/local/lib/python2.7/dist-packages/scrapy/settings/__init__.py", line 317, in update
            for name, value in six.iteritems(values):
          File "/usr/local/lib/python2.7/dist-packages/six.py", line 599, in iteritems
            return d.iteritems(**kw)
        AttributeError: 'list' object has no attribute 'iteritems'
```

**Comment by Digenis** [comment]
Perhaps you have some broken settings
in combination with a local_settings file that doesn't get deployed to scrapyd
(this can explain the different errors).
However because of https://github.com/scrapy/scrapyd/issues/145#issuecomment-219675386
I don't think we should start digging in scrapyd yet.
Please make it work out of scrapyd first
with the help of the portia community where needed.
Then if it still doesn't work on scrapyd, we can look into it.

**Comment by Digenis** [comment]
Closing because of insufficient info
