### ISSUE TITLE
How to format the scrapyd log of a traceback in one line?

### ISSUE THREAD

**Issue by rolele** [scrapy/scrapyd#188]
I setup a ELK stack so each line in the log is send independently and create a document in elastic search.
I generated an error in one of my script to see the log in scrapyd
```
2016-11-06T08:51:01+0000 [twisted.python.log#info] "172.19.0.1" - - [06/Nov/2016:08:51:00 +0000] "GET / HTTP/1.1" 200 749 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.10; rv:49.0) Gecko/20100101 Firefox/49.0"
2016-11-06T08:51:02+0000 [twisted.python.log#info] "172.19.0.1" - - [06/Nov/2016:08:51:02 +0000] "GET /jobs HTTP/1.1" 200 746 "http://localhost:6801/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.10; rv:49.0) Gecko/20100101 Firefox/49.0"
2016-11-06T08:51:03+0000 [twisted.python.log#info] "172.19.0.1" - - [06/Nov/2016:08:51:03 +0000] "GET /logs/kafka_pipeline/spider/203af6e2a3fe11e688a40242ac130004.log HTTP/1.1" 200 617 "http://localhost:6801/jobs" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.10; rv:49.0) Gecko/20100101 Firefox/49.0"
2016-11-06T08:53:48+0000 [twisted.python.log#info] "127.0.0.1" - - [06/Nov/2016:08:53:47 +0000] "POST /addversion.json HTTP/1.1" 200 114 "-" "Python-urllib/3.5"
2016-11-06T08:53:55+0000 [twisted.python.log#info] "127.0.0.1" - - [06/Nov/2016:08:53:53 +0000] "POST /schedule.json HTTP/1.1" 200 91 "-" "curl/7.47.0"
2016-11-06T08:53:58+0000 [-] Process started:  project='kafka_pipeline' spider='spider' job='8c54ac88a3fe11e688a40242ac130004' pid=82 log='/var/lib/scrapyd/logs/kafka_pipeline/spider/8c54ac88a3fe11e688a40242ac130004.log' items='file:///var/lib/scrapyd/items/kafka_pipeline/spider/8c54ac88a3fe11e688a40242ac130004.jl'
2016-11-06T08:53:59+0000 [Launcher,82/stderr] Traceback (most recent call last):
          File "/usr/lib/python3.5/runpy.py", line 184, in _run_module_as_main
            "__main__", mod_spec)
          File "/usr/lib/python3.5/runpy.py", line 85, in _run_code
            exec(code, run_globals)
          File "/usr/local/lib/python3.5/dist-packages/scrapyd/runner.py", line 40, in <module>
            main()
          File "/usr/local/lib/python3.5/dist-packages/scrapyd/runner.py", line 37, in main
            execute()
          File "/usr/local/lib/python3.5/dist-packages/scrapy/cmdline.py", line 142, in execute
            _run_print_help(parser, _run_command, cmd, args, opts)
          File "/usr/local/lib/python3.5/dist-packages/scrapy/cmdline.py", line 88, in _run_print_help
            func(*a, **kw)
          File "/usr/local/lib/python3.5/dist-packages/scrapy/cmdline.py", line 149, in _run_command
            cmd.run(args, opts)
          File "/usr/local/lib/python3.5/dist-packages/scrapy/commands/crawl.py", line 57, in run
            self.crawler_process.crawl(spname, **opts.spargs)
          File "/usr/local/lib/python3.5/dist-packages/scrapy/crawler.py", line 162, in crawl
            crawler = self.create_crawler(crawler_or_spidercls)
          File "/usr/local/lib/python3.5/dist-packages/scrapy/crawler.py", line 190, in create_crawler
            return self._create_crawler(crawler_or_spidercls)
          File "/usr/local/lib/python3.5/dist-packages/scrapy/crawler.py", line 195, in _create_crawler
            return Crawler(spidercls, self.settings)
          File "/usr/local/lib/python3.5/dist-packages/scrapy/crawler.py", line 36, in __init__
            self.stats = load_object(self.settings['STATS_CLASS'])(self)
          File "/tmp/kafka_pipeline-1478422427-muaa0a78.egg/kafka_pipeline/statscollectors.py", line 37, in __init__
          File "/tmp/kafka_pipeline-1478422427-muaa0a78.egg/kafka_pipeline/statscollectors.py", line 33, in __init__
        IndexError: list index out of range
2016-11-06T08:53:59+0000 [-] Process died: exitstatus=1  project='kafka_pipeline' spider='spider' job='8c54ac88a3fe11e688a40242ac130004' pid=82 log='/var/lib/scrapyd/logs/kafka_pipeline/spider/8c54ac88a3fe11e688a40242ac130004.log' items='file:///var/lib/scrapyd/items/kafka_pipeline/spider/8c54ac88a3fe11e688a40242ac130004.jl'
2016-11-06T08:54:01+0000 [twisted.python.log#info] "172.19.0.1" - - [06/Nov/2016:08:54:01 +0000] "GET /jobs HTTP/1.1" 200 1050 "http://localhost:6801/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.10; rv:49.0) Gecko/20100101 Firefox/49.0"
2016-11-06T08:54:03+0000 [twisted.python.log#info] "172.19.0.1" - - [06/Nov/2016:08:54:03 +0000] "GET /logs/kafka_pipeline/spider/8c54ac88a3fe11e688a40242ac130004.log HTTP/1.1" 200 617 "http://localhost:6801/jobs" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.10; rv:49.0) Gecko/20100101 Firefox/49.0"
```

It is usually fine but the Traceback is displayed on many lines and this is what I would like to change.
Is there a way to change that? Thanks

**Comment by Digenis** [comment]
You should be able to parse it because in a log message,
all lines after the first should be indented.

However this only applies to scrapyd.
In scrapy, since 1.0
they are no longer indented.
Which scrapy version do you use?
If the log can no longer be parsed because of the change in 1.0
we should open an issue in scrapy.

**Comment by rolele** [comment]
I use scrapy 1.2.1 with python 3.
But I am interested in the stacktrace that could be caused by the scrapyd deamon. (like the one before).
I think this is the line that render the exception: https://github.com/scrapy/scrapyd/blob/165797e76caebbadbc7fd4c26ce41d2822b3c4e1/scrapyd/webservice.py#L18

Even if they are indented or not, they are on different lines and this is a problem in my case because there will be saved as different documents in ES.
Also if you think about preprocessing the log in logstash and try to aggregate them before inserting into one document this is difficult because you can not garanty the order the log will be received by logstash.

I would love to be able to flatten the log at scrapyd level. This will be less readable for human but way more efficient for elasticsearch.

**Comment by Digenis** [comment]
I commented on scrapy about this
https://github.com/scrapy/scrapy/pull/1731#issuecomment-267962735
and will add a separate issue.

**Comment by jpmckinney** [comment]
This is not a problem in Scrapyd. The log parser shouldn't assume messages are only as long as one line. Log messages follow a consistent format (e.g. starting with a date) - it is not difficult to parse multi-line messages.
