### ISSUE TITLE
Portia Deployment Problem

### ISSUE THREAD

**Issue by JJINDAHOUSE** [scrapy/scrapyd#189]
I wanted to deploy my Portia Project on Scrapyd. However, I received the following error:

```
C:\Users\eric\Desktop\project>scrapyd-deploy
Packing version 1480440269
Traceback (most recent call last):
 File "C:\Program Files\Anaconda2\Scripts\scrapyd-deploy", line 273, in <module>
   main()
 File "C:\Program Files\Anaconda2\Scripts\scrapyd-deploy", line 95, in main
   egg, tmpdir = _build_egg()
 File "C:\Program Files\Anaconda2\Scripts\scrapyd-deploy", line 240, in _build_egg
   retry_on_eintr(check_call, [sys.executable, 'setup.py', 'clean', '-a', 'bdist_egg', '-d', d], stdout=o, stderr=e)
 File "C:\Program Files\Anaconda2\lib\site-packages\scrapy\utils\python.py", line 331, in retry_on_eintr
   return function(*args, **kw)
 File "C:\Program Files\Anaconda2\lib\subprocess.py", line 541, in check_call
   raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['C:\\Program Files\\Anaconda2\\python.exe', 'setup.py', 'clean', '-a', 'bdist_egg', '-d', 'c:\\users\\eric\\appdata\\local\\temp\\scrapydeploy-3ybepr']' returned non-zero exit status 1
```
Can anyone help?

**Comment by Digenis** [comment]
This breaks before uploading to scrapyd
https://github.com/scrapy/scrapyd-client is the place to report this issue.
Also, try executing `C:\Program Files\Anaconda2\python.exe setup.py clean -a bdist_egg -d C:\Users\eric\appdata\local\temp\scrapydeploy-3ybepr` on the shell
and include its output in the issue.

**Comment by JJINDAHOUSE** [comment]
Thank you so much!
