### ISSUE TITLE
a bytes-like object is required, not 'str'

### ISSUE THREAD

**Issue by seozed** [scrapy/scrapyd#227]
```
zeddeMacBook-Air:SpiderKeeper zed$ scrapyd
Traceback (most recent call last):
  File "/Users/zed/.pyenv/versions/3.5.1/bin/scrapyd", line 9, in <module>
    load_entry_point('scrapyd==1.1.1', 'console_scripts', 'scrapyd')()
  File "/Users/zed/.pyenv/versions/3.5.1/lib/python3.5/site-packages/pkg_resources/__init__.py", line 558, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/Users/zed/.pyenv/versions/3.5.1/lib/python3.5/site-packages/pkg_resources/__init__.py", line 2682, in load_entry_point
    return ep.load()
  File "/Users/zed/.pyenv/versions/3.5.1/lib/python3.5/site-packages/pkg_resources/__init__.py", line 2355, in load
    return self.resolve()
  File "/Users/zed/.pyenv/versions/3.5.1/lib/python3.5/site-packages/pkg_resources/__init__.py", line 2361, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/Users/zed/.pyenv/versions/3.5.1/lib/python3.5/site-packages/scrapyd/__init__.py", line 3, in <module>
    version_info = tuple(__version__.split('.')[:3])
TypeError: a bytes-like object is required, not 'str'
```
This prompt appears after a new installation
python : 3.5.1
os: osx 10.12.4

**Comment by seozed** [comment]
Scrapyd does not support python3?

**Comment by redapple** [comment]
Not yet officially but there version 1.2.0a1 that you can try:
https://pypi.python.org/pypi/scrapyd/1.2.0a1

pip install --pre scrapyd
pip install scrapyd==1.2.0a1

**Comment by seozed** [comment]
thx
