### ISSUE TITLE
post request not allowed

### ISSUE THREAD

**Issue by ylu021** [scrapy/scrapyd#240]
when deployed to aws, scrapyd starts fine, and curl does not work when i try to schedule. Below is the error. Where can one config allowed request methods? Thanks.

```
<html>
  <head><title>405 - Method Not Allowed</title></head>
  <body>
    <h1>Method Not Allowed</h1>
    <p>Your browser approached me (at /) with the method "POST".  I only allow the methods HEAD, GET here.</p>
  </body>
</html>
```

**Comment by Digenis** [comment]
Hi, ylu021,
this doesn't seem like a scrapyd response.
scrapyd would respond in json.

You probably need to check your aws instance's configuration.

**Comment by tsauzeau** [comment]
Hey,

I have the same kind of issue (but on docker with portia):
```
scrapyd_1  | 2017-11-10T11:40:24+0000 [twisted.python.log#info] "172.17.0.3" - - [10/Nov/2017:11:40:23 +0000] "POST / HTTP/1.1" 405 233 "-" "python-requests/2.18.4"
portia_1   | Internal Server Error: /api/projects/leboncoin/spiders/www.leboncoin.fr/schedule
portia_1   | Traceback (most recent call last):
portia_1   |   File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/exception.py", line 39, in inner
portia_1   |     response = get_response(request)
portia_1   |   File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 187, in _get_response
portia_1   |     response = self.process_exception_by_middleware(e, request)
portia_1   |   File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 185, in _get_response
portia_1   |     response = wrapped_callback(request, *callback_args, **callback_kwargs)
portia_1   |   File "/usr/local/lib/python2.7/dist-packages/django/views/decorators/csrf.py", line 58, in wrapped_view
portia_1   |     return view_func(*args, **kwargs)
portia_1   |   File "/usr/local/lib/python2.7/dist-packages/rest_framework/viewsets.py", line 90, in view
portia_1   |     return self.dispatch(request, *args, **kwargs)
portia_1   |   File "/usr/local/lib/python2.7/dist-packages/django/utils/decorators.py", line 185, in inner
portia_1   |     return func(*args, **kwargs)
portia_1   |   File "/app/portia_server/portia_api/resources/route.py", line 74, in dispatch
portia_1   |     return super(JsonApiRoute, self).dispatch(request, *args, **kwargs)
portia_1   |   File "/usr/local/lib/python2.7/dist-packages/rest_framework/views.py", line 489, in dispatch
portia_1   |     response = self.handle_exception(exc)
portia_1   |   File "/app/portia_server/portia_api/resources/route.py", line 77, in handle_exception
portia_1   |     response = super(JsonApiRoute, self).handle_exception(exc)
portia_1   |   File "/usr/local/lib/python2.7/dist-packages/rest_framework/views.py", line 446, in handle_exception
portia_1   |     response = exception_handler(exc, context)
portia_1   |   File "/app/portia_server/portia_api/jsonapi/exceptions.py", line 67, in jsonapi_exception_handler
portia_1   |     exc.detail = render_exception(exc.status_code, exc.detail)
portia_1   |   File "/app/portia_server/portia_api/jsonapi/exceptions.py", line 30, in render_exception
portia_1   |     ('title', get_status_title(status_code)),
portia_1   |   File "/app/portia_server/portia_api/jsonapi/utils.py", line 94, in get_status_title
portia_1   |     return status_codes[status_code][0].replace('_', ' ').title()
portia_1   | KeyError: '\n<html>\n  <head><title>405 - Method Not Allowed</title></head>\n  <body>\n    <h1>Method Not Allowed</h1>\n    <p>Your browser approached me (at /) with the method "POST".  I only allow the methods HEAD, GET here.</p>\n  </body>\n</html>\n'
```

scrapyd respond with a 405, portia throw the error after (with the same text than @ylu021).

**Comment by jpmckinney** [comment]
Closing old support request that does not seem related to Scrapyd.
