### ISSUE TITLE
scrapyd cant install install_requires from setup.py

### ISSUE THREAD

**Issue by junejie** [scrapy/scrapyd#246]
I build the egg using `scrapyd-deploy --build-egg=dist/articles.egg`

I deploy it using curl and it trow error.

Error: 

```
Traceback (most recent call last):
      File "/User/accountname/lib/python3.5/site-packages/twisted/web/http.py", line 2104, in allContentReceived
        req.requestReceived(command, path, version)
      File "/User/accountname/lib/python3.5/site-packages/twisted/web/http.py", line 866, in requestReceived
        self.process()
      File "/User/accountname/lib/python3.5/site-packages/twisted/web/server.py", line 195, in process
        self.render(resrc)
      File "/User/accountname/lib/python3.5/site-packages/twisted/web/server.py", line 255, in render
        body = resrc.render(self)
    --- <exception caught here> ---
      File "/User/accountname/lib/python3.5/site-packages/scrapyd/webservice.py", line 21, in render
        return JsonResource.render(self, txrequest).encode('utf-8')
      File "/User/accountname/lib/python3.5/site-packages/scrapyd/utils.py", line 20, in render
        r = resource.Resource.render(self, txrequest)
      File "/User/accountname/lib/python3.5/site-packages/twisted/web/resource.py", line 250, in render
        return m(request)
      File "/User/accountname/lib/python3.5/site-packages/scrapyd/webservice.py", line 86, in render_POST
        spiders = get_spider_list(project, version=version)
      File "/User/accountname/lib/python3.5/site-packages/scrapyd/utils.py", line 137, in get_spider_list
        raise RuntimeError(msg.encode('unicode_escape') if six.PY2 else msg)
    builtins.RuntimeError: Traceback (most recent call last):
      File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/runpy.py", line 193, in _run_module_as_main
        "__main__", mod_spec)
      File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/runpy.py", line 85, in _run_code
        exec(code, run_globals)
      File "/User/accountname/lib/python3.5/site-packages/scrapyd/runner.py", line 40, in <module>
        main()
      File "/User/accountname/lib/python3.5/site-packages/scrapyd/runner.py", line 37, in main
        execute()
      File "/User/accountname/lib/python3.5/site-packages/scrapy/cmdline.py", line 109, in execute
        settings = get_project_settings()
      File "/User/accountname/lib/python3.5/site-packages/scrapy/utils/project.py", line 68, in get_project_settings
        settings.setmodule(settings_module_path, priority='project')
      File "/User/accountname/lib/python3.5/site-packages/scrapy/settings/__init__.py", line 292, in setmodule
        module = import_module(module)
      File "/User/accountname/lib/python3.5/importlib/__init__.py", line 126, in import_module
        return _bootstrap._gcd_import(name[level:], package, level)
      File "<frozen importlib._bootstrap>", line 985, in _gcd_import
      File "<frozen importlib._bootstrap>", line 968, in _find_and_load
      File "<frozen importlib._bootstrap>", line 957, in _find_and_load_unlocked
      File "<frozen importlib._bootstrap>", line 664, in _load_unlocked
      File "<frozen importlib._bootstrap>", line 634, in _load_backward_compatible
      File "/private/var/folders/z6/5t65nrm12gzfn9ct44qk27wm0000gn/T/articles-r1-q1kuw69y.egg/articles/settings.py", line 4, in <module>
    ImportError: No module named 'constance'
```

**Comment by Digenis** [comment]
Hi, @junejie,

currently there's no such feature in scrapyd.
You need to install them manually.

**Comment by cleocn** [comment]
i forked and fix this.

https://github.com/cleocn/scrapyd/commit/f74627a8852b2128457ab0d811e14e58a502c3c8

**Comment by cleocn** [comment]
**setup.py:**

from setuptools import setup, find_packages

setup(
    name         = 'project',
    version      = '1.0',
    packages     = find_packages(),
    install_requires = ["scrapy-sentry", 
                        "scrapy", 
                        "selenium", 
                        "mysql-connector-python",
                        "numpy"],
    entry_points = {'scrapy': ['settings = seleniumcrawler.settings']}
)

**scrapyd output：**

`
2018-01-11T16:48:01+0800 [-] Timing out client: IPv4Address(TCP, '10.255.0.2', 62196)
2018-01-11T16:48:22+0800 [stdout#info] Collecting scrapy-sentry
2018-01-11T16:48:23+0800 [stdout#info]   Downloading scrapy-sentry-0.8.0.tar.gz
2018-01-11T16:48:25+0800 [stdout#info] Requirement already satisfied: Scrapy>=1.4.0 in /usr/local/lib/python2.7/dist-packages (from scrapy-sentry)
2018-01-11T16:48:25+0800 [stdout#info] Collecting raven>=6.3.0 (from scrapy-sentry)
2018-01-11T16:48:25+0800 [stdout#info]   Downloading raven-6.4.0-py2.py3-none-any.whl (282kB)
    100% |################################| 286kB 528kB/s 
2018-01-11T16:48:26+0800 [stdout#info] Requirement already satisfied: six>=1.11.0 in /usr/local/lib/python2.7/dist-packages (from scrapy-sentry)
2018-01-11T16:48:26+0800 [stdout#info] Requirement already satisfied: PyDispatcher>=2.0.5 in /usr/local/lib/python2.7/dist-packages (from Scrapy>=1.4.0->scrapy-sentry)
2018-01-11T16:48:26+0800 [stdout#info] Requirement already satisfied: Twisted>=13.1.0 in /usr/local/lib/python2.7/dist-packages (from Scrapy>=1.4.0->scrapy-sentry)
2018-01-11T16:48:26+0800 [stdout#info] Requirement already satisfied: lxml in /usr/local/lib/python2.7/dist-packages (from Scrapy>=1.4.0->scrapy-sentry)
2018-01-11T16:48:26+0800 [stdout#info] Requirement already satisfied: service-identity in /usr/local/lib/python2.7/dist-packages (from Scrapy>=1.4.0->scrapy-sentry)
2018-01-11T16:48:26+0800 [stdout#info] Requirement already satisfied: w3lib>=1.17.0 in /usr/local/lib/python2.7/dist-packages (from Scrapy>=1.4.0->scrapy-sentry)
2018-01-11T16:48:26+0800 [stdout#info] Requirement already satisfied: pyOpenSSL in /usr/local/lib/python2.7/dist-packages (from Scrapy>=1.4.0->scrapy-sentry)
2018-01-11T16:48:26+0800 [stdout#info] Requirement already satisfied: parsel>=1.1 in /usr/local/lib/python2.7/dist-packages (from Scrapy>=1.4.0->scrapy-sentry)
2018-01-11T16:48:26+0800 [stdout#info] Requirement already satisfied: cssselect>=0.9 in /usr/local/lib/python2.7/dist-packages (from Scrapy>=1.4.0->scrapy-sentry)
2018-01-11T16:48:26+0800 [stdout#info] Requirement already satisfied: queuelib in /usr/local/lib/python2.7/dist-packages (from Scrapy>=1.4.0->scrapy-sentry)
2018-01-11T16:48:26+0800 [stdout#info] Collecting contextlib2; python_version < "3.2" (from raven>=6.3.0->scrapy-sentry)
2018-01-11T16:48:26+0800 [stdout#info]   Downloading contextlib2-0.5.5-py2.py3-none-any.whl
2018-01-11T16:48:26+0800 [stdout#info] Requirement already satisfied: zope.interface>=3.6.0 in /usr/local/lib/python2.7/dist-packages (from Twisted>=13.1.0->Scrapy>=1.4.0->scrapy-sentry)
2018-01-11T16:48:26+0800 [stdout#info] Requirement already satisfied: constantly>=15.1 in /usr/local/lib/python2.7/dist-packages (from Twisted>=13.1.0->Scrapy>=1.4.0->scrapy-sentry)
2018-01-11T16:48:26+0800 [stdout#info] Requirement already satisfied: incremental>=16.10.1 in /usr/local/lib/python2.7/dist-packages (from Twisted>=13.1.0->Scrapy>=1.4.0->scrapy-sentry)
2018-01-11T16:48:26+0800 [stdout#info] Requirement already satisfied: Automat>=0.3.0 in /usr/local/lib/python2.7/dist-packages (from Twisted>=13.1.0->Scrapy>=1.4.0->scrapy-sentry)
2018-01-11T16:48:26+0800 [stdout#info] Requirement already satisfied: hyperlink>=17.1.1 in /usr/local/lib/python2.7/dist-packages (from Twisted>=13.1.0->Scrapy>=1.4.0->scrapy-sentry)
2018-01-11T16:48:26+0800 [stdout#info] Requirement already satisfied: attrs in /usr/local/lib/python2.7/dist-packages (from service-identity->Scrapy>=1.4.0->scrapy-sentry)
2018-01-11T16:48:26+0800 [stdout#info] Requirement already satisfied: pyasn1 in /usr/local/lib/python2.7/dist-packages (from service-identity->Scrapy>=1.4.0->scrapy-sentry)
2018-01-11T16:48:26+0800 [stdout#info] Requirement already satisfied: pyasn1-modules in /usr/local/lib/python2.7/dist-packages (from service-identity->Scrapy>=1.4.0->scrapy-sentry)
2018-01-11T16:48:26+0800 [stdout#info] Requirement already satisfied: cryptography>=2.1.4 in /usr/local/lib/python2.7/dist-packages (from pyOpenSSL->Scrapy>=1.4.0->scrapy-sentry)
2018-01-11T16:48:26+0800 [stdout#info] Requirement already satisfied: setuptools in /usr/local/lib/python2.7/dist-packages (from zope.interface>=3.6.0->Twisted>=13.1.0->Scrapy>=1.4.0->scrapy-sentry)
2018-01-11T16:48:26+0800 [stdout#info] Requirement already satisfied: cffi>=1.7; platform_python_implementation != "PyPy" in /usr/local/lib/python2.7/dist-packages (from cryptography>=2.1.4->pyOpenSSL->Scrapy>=1.4.0->scrapy-sentry)
2018-01-11T16:48:26+0800 [stdout#info] Requirement already satisfied: enum34; python_version < "3" in /usr/local/lib/python2.7/dist-packages (from cryptography>=2.1.4->pyOpenSSL->Scrapy>=1.4.0->scrapy-sentry)
2018-01-11T16:48:26+0800 [stdout#info] Requirement already satisfied: asn1crypto>=0.21.0 in /usr/local/lib/python2.7/dist-packages (from cryptography>=2.1.4->pyOpenSSL->Scrapy>=1.4.0->scrapy-sentry)
2018-01-11T16:48:27+0800 [stdout#info] Requirement already satisfied: idna>=2.1 in /usr/local/lib/python2.7/dist-packages (from cryptography>=2.1.4->pyOpenSSL->Scrapy>=1.4.0->scrapy-sentry)
2018-01-11T16:48:27+0800 [stdout#info] Requirement already satisfied: ipaddress; python_version < "3" in /usr/local/lib/python2.7/dist-packages (from cryptography>=2.1.4->pyOpenSSL->Scrapy>=1.4.0->scrapy-sentry)
2018-01-11T16:48:27+0800 [stdout#info] Requirement already satisfied: pycparser in /usr/local/lib/python2.7/dist-packages (from cffi>=1.7; platform_python_implementation != "PyPy"->cryptography>=2.1.4->pyOpenSSL->Scrapy>=1.4.0->scrapy-sentry)
2018-01-11T16:48:27+0800 [stdout#info] Installing collected packages: contextlib2, raven, scrapy-sentry
2018-01-11T16:48:27+0800 [stdout#info]   Running setup.py install for scrapy-sentry: started
2018-01-11T16:48:27+0800 [stdout#info]     Running setup.py install for scrapy-sentry: finished with status 'done'
2018-01-11T16:48:27+0800 [stdout#info] Successfully installed contextlib2-0.5.5 raven-6.4.0 scrapy-sentry-0.8.0
2018-01-11T16:48:27+0800 [stdout#info] Requirement already satisfied: scrapy in /usr/local/lib/python2.7/dist-packages
2018-01-11T16:48:27+0800 [stdout#info] Requirement already satisfied: PyDispatcher>=2.0.5 in /usr/local/lib/python2.7/dist-packages (from scrapy)
2018-01-11T16:48:27+0800 [stdout#info] Requirement already satisfied: Twisted>=13.1.0 in /usr/local/lib/python2.7/dist-packages (from scrapy)
2018-01-11T16:48:27+0800 [stdout#info] Requirement already satisfied: lxml in /usr/local/lib/python2.7/dist-packages (from scrapy)
2018-01-11T16:48:27+0800 [stdout#info] Requirement already satisfied: service-identity in /usr/local/lib/python2.7/dist-packages (from scrapy)
2018-01-11T16:48:27+0800 [stdout#info] Requirement already satisfied: w3lib>=1.17.0 in /usr/local/lib/python2.7/dist-packages (from scrapy)
2018-01-11T16:48:27+0800 [stdout#info] Requirement already satisfied: pyOpenSSL in /usr/local/lib/python2.7/dist-packages (from scrapy)
2018-01-11T16:48:27+0800 [stdout#info] Requirement already satisfied: parsel>=1.1 in /usr/local/lib/python2.7/dist-packages (from scrapy)
2018-01-11T16:48:27+0800 [stdout#info] Requirement already satisfied: cssselect>=0.9 in /usr/local/lib/python2.7/dist-packages (from scrapy)
2018-01-11T16:48:27+0800 [stdout#info] Requirement already satisfied: six>=1.5.2 in /usr/local/lib/python2.7/dist-packages (from scrapy)
2018-01-11T16:48:27+0800 [stdout#info] Requirement already satisfied: queuelib in /usr/local/lib/python2.7/dist-packages (from scrapy)
2018-01-11T16:48:27+0800 [stdout#info] Requirement already satisfied: zope.interface>=3.6.0 in /usr/local/lib/python2.7/dist-packages (from Twisted>=13.1.0->scrapy)
2018-01-11T16:48:27+0800 [stdout#info] Requirement already satisfied: constantly>=15.1 in /usr/local/lib/python2.7/dist-packages (from Twisted>=13.1.0->scrapy)
2018-01-11T16:48:27+0800 [stdout#info] Requirement already satisfied: incremental>=16.10.1 in /usr/local/lib/python2.7/dist-packages (from Twisted>=13.1.0->scrapy)
2018-01-11T16:48:27+0800 [stdout#info] Requirement already satisfied: Automat>=0.3.0 in /usr/local/lib/python2.7/dist-packages (from Twisted>=13.1.0->scrapy)
2018-01-11T16:48:27+0800 [stdout#info] Requirement already satisfied: hyperlink>=17.1.1 in /usr/local/lib/python2.7/dist-packages (from Twisted>=13.1.0->scrapy)
2018-01-11T16:48:27+0800 [stdout#info] Requirement already satisfied: attrs in /usr/local/lib/python2.7/dist-packages (from service-identity->scrapy)
2018-01-11T16:48:27+0800 [stdout#info] Requirement already satisfied: pyasn1 in /usr/local/lib/python2.7/dist-packages (from service-identity->scrapy)
2018-01-11T16:48:27+0800 [stdout#info] Requirement already satisfied: pyasn1-modules in /usr/local/lib/python2.7/dist-packages (from service-identity->scrapy)
2018-01-11T16:48:27+0800 [stdout#info] Requirement already satisfied: cryptography>=2.1.4 in /usr/local/lib/python2.7/dist-packages (from pyOpenSSL->scrapy)
2018-01-11T16:48:27+0800 [stdout#info] Requirement already satisfied: setuptools in /usr/local/lib/python2.7/dist-packages (from zope.interface>=3.6.0->Twisted>=13.1.0->scrapy)
2018-01-11T16:48:27+0800 [stdout#info] Requirement already satisfied: cffi>=1.7; platform_python_implementation != "PyPy" in /usr/local/lib/python2.7/dist-packages (from cryptography>=2.1.4->pyOpenSSL->scrapy)
2018-01-11T16:48:27+0800 [stdout#info] Requirement already satisfied: enum34; python_version < "3" in /usr/local/lib/python2.7/dist-packages (from cryptography>=2.1.4->pyOpenSSL->scrapy)
2018-01-11T16:48:27+0800 [stdout#info] Requirement already satisfied: asn1crypto>=0.21.0 in /usr/local/lib/python2.7/dist-packages (from cryptography>=2.1.4->pyOpenSSL->scrapy)
2018-01-11T16:48:27+0800 [stdout#info] Requirement already satisfied: idna>=2.1 in /usr/local/lib/python2.7/dist-packages (from cryptography>=2.1.4->pyOpenSSL->scrapy)
2018-01-11T16:48:27+0800 [stdout#info] Requirement already satisfied: ipaddress; python_version < "3" in /usr/local/lib/python2.7/dist-packages (from cryptography>=2.1.4->pyOpenSSL->scrapy)
2018-01-11T16:48:27+0800 [stdout#info] Requirement already satisfied: pycparser in /usr/local/lib/python2.7/dist-packages (from cffi>=1.7; platform_python_implementation != "PyPy"->cryptography>=2.1.4->pyOpenSSL->scrapy)
2018-01-11T16:48:28+0800 [stdout#info] Requirement already satisfied: selenium in /usr/local/lib/python2.7/dist-packages
2018-01-11T16:48:28+0800 [stdout#info] Requirement already satisfied: mysql-connector-python in /usr/local/lib/python2.7/dist-packages
2018-01-11T16:48:28+0800 [stdout#info] Requirement already satisfied: numpy in /usr/local/lib/python2.7/dist-packages
2018-01-11T16:48:29+0800 [twisted.python.log#info] "10.255.0.2" - - [11/Jan/2018:08:48:22 +0000] "POST /addversion.json HTTP/1.1" 200 103 "-" "Python-urllib/2.7"`

**Comment by jpmckinney** [comment]
See https://github.com/scrapy/scrapyd-client/issues/79 instead.
