### ISSUE TITLE
error when run a spidero project

### ISSUE THREAD

**Issue by allenzhang721** [scrapy/scrapyd#270]
When i run my project on scrapyd , there was a error that I can't fix it my

Scrapyd Version:
1.2.0

Operating System:
CentOS 7.2 x86_64

Python Version:
3.6.1

error message:
2018-01-17 23:41:09 [twisted] CRITICAL: Unhandled error in Deferred:
2018-01-17 23:41:09 [twisted] CRITICAL: 
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/twisted/internet/defer.py", line 1386, in _inlineCallbacks
    result = g.send(result)
  File "/usr/local/lib/python3.6/site-packages/scrapy/crawler.py", line 80, in crawl
    self.engine = self._create_engine()
  File "/usr/local/lib/python3.6/site-packages/scrapy/crawler.py", line 105, in _create_engine
    return ExecutionEngine(self, lambda _: self.stop())
  File "/usr/local/lib/python3.6/site-packages/scrapy/core/engine.py", line 70, in __init__
    self.scraper = Scraper(crawler)
  File "/usr/local/lib/python3.6/site-packages/scrapy/core/scraper.py", line 71, in __init__
    self.itemproc = itemproc_cls.from_crawler(crawler)
  File "/usr/local/lib/python3.6/site-packages/scrapy/middleware.py", line 58, in from_crawler
    return cls.from_settings(crawler.settings, crawler)
  File "/usr/local/lib/python3.6/site-packages/scrapy/middleware.py", line 36, in from_settings
    mw = mwcls.from_crawler(crawler)
  File "/usr/local/lib/python3.6/site-packages/scrapy/pipelines/media.py", line 68, in from_crawler
    pipe = cls.from_settings(crawler.settings)
  File "/usr/local/lib/python3.6/site-packages/scrapy/pipelines/images.py", line 98, in from_settings
    return cls(store_uri, settings=settings)
  File "/usr/local/lib/python3.6/site-packages/scrapy/pipelines/images.py", line 52, in __init__
    download_func=download_func)
  File "/usr/local/lib/python3.6/site-packages/scrapy/pipelines/files.py", line 276, in __init__
    self.store = self._get_store(store_uri)
  File "/usr/local/lib/python3.6/site-packages/scrapy/pipelines/files.py", line 315, in _get_store
    return store_cls(uri)
  File "/usr/local/lib/python3.6/site-packages/scrapy/pipelines/files.py", line 48, in __init__
    self._mkdir(self.basedir)
  File "/usr/local/lib/python3.6/site-packages/scrapy/pipelines/files.py", line 77, in _mkdir
    os.makedirs(dirname)
  File "/usr/local/lib/python3.6/os.py", line 210, in makedirs
    makedirs(head, mode, exist_ok)
  File "/usr/local/lib/python3.6/os.py", line 210, in makedirs
    makedirs(head, mode, exist_ok)
  File "/usr/local/lib/python3.6/os.py", line 220, in makedirs
    mkdir(name, mode)
NotADirectoryError: [Errno 20] Not a directory: '/tmp/botaiWeiboSpider-1516201841-gatbm0ct.egg/botaiWeiboSpider'

**Comment by superzadeh** [comment]
Also running into this @allenzhang721 , any clue on what was causing it? I'm running scrapyd in docker, and trying to deploy from portia.
