### ISSUE TITLE
scrapyd jobs are pending forever

### ISSUE THREAD

**Issue by alexanderlukanin13** [scrapy/scrapyd#279]
After using scrapyd successfully for many months, I've suddenly ran into problem. Scrapyd tasks are stuck in Pending state. Scheduler doesn't run them.

`daemonstatus.json` seems OK:

    {"node_name": "data", "status": "ok", "pending": 30, "running": 0, "finished": 100}

If I restart scrapyd via `supervisorctl restart scrapyd`, it goes back to normal.

It may or may not be related to low-memory situation that was happening periodically for an unrelated reason. I see following in `supervisord` log for `scrapyd`:

    2018-04-28T20:01:34+0300 [twisted.python.log#info] "127.0.0.1" - - [28/Apr/2018:17:01:20 +0000] "POST /schedule.json HTTP/1.1" 200 83 "-" "python-requests/2.13.0"
    2018-04-28T20:01:36+0300 [twisted.internet.defer#critical] Unhandled error in Deferred:
    2018-04-28T20:01:36+0300 [twisted.internet.defer#critical] 
            Traceback (most recent call last):
              File "/home/bm/.pyenv/versions/3.6.3/envs/bm/lib/python3.6/site-packages/scrapyd/poller.py", line 25, in poll
                returnValue(self.dq.put(self._message(msg, p)))
              File "/home/bm/.pyenv/versions/3.6.3/envs/bm/lib/python3.6/site-packages/twisted/internet/defer.py", line 1688, in put
                self.waiting.pop(0).callback(obj)
              File "/home/bm/.pyenv/versions/3.6.3/envs/bm/lib/python3.6/site-packages/twisted/internet/defer.py", line 459, in callback
                self._startRunCallbacks(result)
              File "/home/bm/.pyenv/versions/3.6.3/envs/bm/lib/python3.6/site-packages/twisted/internet/defer.py", line 567, in _startRunCallbacks
                self._runCallbacks()
            --- <exception caught here> ---
              File "/home/bm/.pyenv/versions/3.6.3/envs/bm/lib/python3.6/site-packages/twisted/internet/defer.py", line 653, in _runCallbacks
                current.result = callback(current.result, *args, **kw)
              File "/home/bm/.pyenv/versions/3.6.3/envs/bm/lib/python3.6/site-packages/scrapyd/launcher.py", line 47, in _spawn_process
                reactor.spawnProcess(pp, sys.executable, args=args, env=env)
              File "/home/bm/.pyenv/versions/3.6.3/envs/bm/lib/python3.6/site-packages/twisted/internet/posixbase.py", line 340, in spawnProcess
                processProtocol, uid, gid, childFDs)
              File "/home/bm/.pyenv/versions/3.6.3/envs/bm/lib/python3.6/site-packages/twisted/internet/process.py", line 745, in __init__
                self._fork(path, uid, gid, executable, args, environment, fdmap=fdmap)
              File "/home/bm/.pyenv/versions/3.6.3/envs/bm/lib/python3.6/site-packages/twisted/internet/process.py", line 420, in _fork
                self.pid = os.fork()
            builtins.OSError: [Errno 12] Cannot allocate memory

Scrapyd config:

    [scrapyd]
    eggs_dir          = /var/lib/scrapyd/eggs
    logs_dir          = /var/lib/scrapyd/logs
    items_dir         = /var/lib/scrapyd/items
    dbs_dir           = /var/lib/scrapyd/dbs
    jobs_to_keep      = 200
    max_proc          = 2
    max_proc_per_cpu  = 1
    finished_to_keep  = 200
    poll_interval     = 5
    bind_address      = 127.0.0.1
    http_port         = 6800
    debug             = off
    runner            = scrapyd.runner
    application       = scrapyd.app.application
    launcher          = scrapyd.launcher.Launcher

    [services]
    schedule.json     = scrapyd.webservice.Schedule
    cancel.json       = scrapyd.webservice.Cancel
    addversion.json   = scrapyd.webservice.AddVersion
    listprojects.json = scrapyd.webservice.ListProjects
    listversions.json = scrapyd.webservice.ListVersions
    listspiders.json  = scrapyd.webservice.ListSpiders
    delproject.json   = scrapyd.webservice.DeleteProject
    delversion.json   = scrapyd.webservice.DeleteVersion
    listjobs.json     = scrapyd.webservice.ListJobs
    daemonstatus.json = scrapyd.webservice.DaemonStatus

Package versions:

    Scrapy==1.3.3
    scrapy-djangoitem==1.1.1
    scrapy-fake-useragent==1.0.4
    scrapy-proxies==0.3
    scrapy-splash==0.7.2
    scrapyd==1.2.0
    scrapyd-client==1.1.0

**Comment by zjjxcxj** [comment]
Hello, how do you solve this problem?

**Comment by francima961** [comment]
Need help with this one too please

**Comment by alexanderlukanin13** [comment]
@zjjxcxj Problem didn't occur anymore after adding more RAM. I guess once `os.fork` fails, task goes into 
a broken state and is pending forever...

**Comment by zjjxcxj** [comment]
@alexanderlukanin13  Thanks for your reply! I have solved it in the same way.

**Comment by Digenis** [comment]
@alexanderlukanin13, which twisted version did you use?

@zjjxcxj, do you also use scrapy-django-item? Do you use scrapy-splash?

**Comment by alexanderlukanin13** [comment]
@Digenis `twisted==17.1.0`

**Comment by jpmckinney** [comment]
Solution has been found above, so closing.
