### ISSUE TITLE
Activating invalid egg doesn't raise helpful exception

### ISSUE THREAD

**Issue by StrikerUnit** [scrapy/scrapyd#282]
Hi,

I just start using Scrapy, found this error and don't know how to fix this.

Python 3.6.5 :: Anaconda custom (x86_64)

```
	Traceback (most recent call last):
	  File "/Users/homerun/anaconda3/lib/python3.6/site-packages/twisted/web/http.py", line 2145, in allContentReceived
	    req.requestReceived(command, path, version)
	  File "/Users/homerun/anaconda3/lib/python3.6/site-packages/twisted/web/http.py", line 890, in requestReceived
	    self.process()
	  File "/Users/homerun/anaconda3/lib/python3.6/site-packages/twisted/web/server.py", line 197, in process
	    self.render(resrc)
	  File "/Users/homerun/anaconda3/lib/python3.6/site-packages/twisted/web/server.py", line 257, in render
	    body = resrc.render(self)
	--- <exception caught here> ---
	  File "/Users/homerun/anaconda3/lib/python3.6/site-packages/scrapyd/webservice.py", line 21, in render
	    return JsonResource.render(self, txrequest).encode('utf-8')
	  File "/Users/homerun/anaconda3/lib/python3.6/site-packages/scrapyd/utils.py", line 20, in render
	    r = resource.Resource.render(self, txrequest)
	  File "/Users/homerun/anaconda3/lib/python3.6/site-packages/twisted/web/resource.py", line 250, in render
	    return m(request)
	  File "/Users/homerun/anaconda3/lib/python3.6/site-packages/scrapyd/webservice.py", line 86, in render_POST
	    spiders = get_spider_list(project, version=version)
	  File "/Users/homerun/anaconda3/lib/python3.6/site-packages/scrapyd/utils.py", line 137, in get_spider_list
	    raise RuntimeError(msg.encode('unicode_escape') if six.PY2 else msg)
	builtins.RuntimeError: Traceback (most recent call last):
	  File "/Users/homerun/anaconda3/lib/python3.6/runpy.py", line 193, in _run_module_as_main
	    "__main__", mod_spec)
	  File "/Users/homerun/anaconda3/lib/python3.6/runpy.py", line 85, in _run_code
	    exec(code, run_globals)
	  File "/Users/homerun/anaconda3/lib/python3.6/site-packages/scrapyd/runner.py", line 40, in <module>
	    main()
	  File "/Users/homerun/anaconda3/lib/python3.6/site-packages/scrapyd/runner.py", line 35, in main
	    with project_environment(project):
	  File "/Users/homerun/anaconda3/lib/python3.6/contextlib.py", line 81, in __enter__
	    return next(self.gen)
	  File "/Users/homerun/anaconda3/lib/python3.6/site-packages/scrapyd/runner.py", line 23, in project_environment
	    activate_egg(eggpath)
	  File "/Users/homerun/anaconda3/lib/python3.6/site-packages/scrapyd/eggutils.py", line 9, in activate_egg
	    d = next(pkg_resources.find_distributions(eggpath))
	TypeError: 'tuple' object is not an iterator
```

**Comment by teryaew** [comment]
+1

**Comment by riklaunim** [comment]
Same with Python 3.7 right now. Latest scrapy and scrapyd. Created scrapy project, then a black spider, made an egg with setup.py bdist_egg to then call
`curl http://localhost:6800/addversion.json -F project=projekt -F version=r1 -F egg=dist/projekt-0.1-py3.7.egg`
within a virtualenv with scrapy/scrapyd etc.

**Comment by my8100** [comment]
@riklaunim 
There should be an @ sign: `-F egg=@dist/projekt-0.1-py3.7.egg`

**Comment by riklaunim** [comment]
oh, nice. That works.

**Comment by my8100** [comment]
## `-F egg=dist/project-1.0-py3.7.egg`
(py3) ubuntu@ubuntu:~ /Documents/demo$ curl http://localhost:6800/addversion.json -F project=myproject -F version=r1 -F egg=dist/project-1.0-py3.7.egg
{"node_name": "ubuntu", "status": "error", "message": "Traceback (most recent call last):\n  File \"/home/ubuntu/anaconda3/envs/py3/lib/python3.7/runpy.py\", line 193, in _run_module_as_main\n    \"__main__\", mod_spec)\n  File \"/home/ubuntu/anaconda3/envs/py3/lib/python3.7/runpy.py\", line 85, in _run_code\n    exec(code, run_globals)\n  File \"/home/ubuntu/anaconda3/envs/py3/lib/python3.7/site-packages/scrapyd/runner.py\", line 40, in <module>\n    main()\n  File \"/home/ubuntu/anaconda3/envs/py3/lib/python3.7/site-packages/scrapyd/runner.py\", line 35, in main\n    with project_environment(project):\n  File \"/home/ubuntu/anaconda3/envs/py3/lib/python3.7/contextlib.py\", line 112, in __enter__\n    return next(self.gen)\n  File \"/home/ubuntu/anaconda3/envs/py3/lib/python3.7/site-packages/scrapyd/runner.py\", line 23, in project_environment\n    activate_egg(eggpath)\n  File \"/home/ubuntu/anaconda3/envs/py3/lib/python3.7/site-packages/scrapyd/eggutils.py\", line 9, in activate_egg\n    d = next(pkg_resources.find_distributions(eggpath))\nTypeError: 'tuple' object is not an iterator\n"}
## `-F egg=@dist/project-1.0-py3.7.egg`
(py3) ubuntu@ubuntu:~/Documents/demo$ curl http://localhost:6800/addversion.json -F project=myproject -F version=r1 -F egg=@dist/project-1.0-py3.7.egg
{"node_name": "ubuntu", "status": "ok", "project": "myproject", "version": "r1", "spiders": 2}

**Comment by Digenis** [comment]
It is a bug. The expected behaviour is raising "ValueError('Uknown or corrupt egg')"
activate_egg relied on find_distributions to let a StopIteration bubble up from somewhere.
Now it returns an empty tuple instead of an iterator.
This may be related to PEP-479 or other python3 changes.
