### ISSUE TITLE
Can not deploy spiders to scrapyd when scrapyd has more than 500 spiders.

### ISSUE THREAD

**Issue by ZakiHe** [scrapy/scrapyd#291]
I'm using scrapyd in an ubuntu docker. Now it matains more than 500 spiders. But recently, I found that the deploy api not work any more. I tried to restart scrapyd. But once it shut down, it can not start any more, unless I reduce the number of spider on it. It seems that it was cased by bug in twisted for linux.
Do you have any ideas? Thanks in advance.

![20180706111614](https://user-images.githubusercontent.com/20454502/42358203-0d263848-810e-11e8-9a78-c6bfae16dc18.png)
 
Following is the error details:

```
Unhandled Error
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/twisted/application/app.py", line 662, in run
    runApp(config)
  File "/usr/local/lib/python2.7/dist-packages/twisted/scripts/twistd.py", line 25, in runApp
    _SomeApplicationRunner(config).run()
  File "/usr/local/lib/python2.7/dist-packages/twisted/application/app.py", line 380, in run
    self.application = self.createOrGetApplication()
  File "/usr/local/lib/python2.7/dist-packages/twisted/application/app.py", line 445, in createOrGetApplication
    application = getApplication(self.config, passphrase)
--- <exception caught here> ---
  File "/usr/local/lib/python2.7/dist-packages/twisted/application/app.py", line 456, in getApplication
    application = service.loadApplication(filename, style, passphrase)
  File "/usr/local/lib/python2.7/dist-packages/twisted/application/service.py", line 412, in loadApplication
    application = sob.loadValueFromFile(filename, 'application')
  File "/usr/local/lib/python2.7/dist-packages/twisted/persisted/sob.py", line 177, in loadValueFromFile
    eval(codeObj, d, d)
  File "/usr/local/lib/python2.7/dist-packages/scrapyd/txapp.py", line 3, in <module>
    application = get_application()
  File "/usr/local/lib/python2.7/dist-packages/scrapyd/__init__.py", line 15, in get_application
    return appfunc(config)
  File "/usr/local/lib/python2.7/dist-packages/scrapyd/app.py", line 32, in application
    laucls = load_object(laupath)
  File "/usr/local/lib/python2.7/dist-packages/scrapy/utils/misc.py", line 44, in load_object
    mod = import_module(module)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/usr/local/lib/python2.7/dist-packages/scrapyd/launcher.py", line 5, in <module>
    from twisted.internet import reactor, defer, protocol, error
  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/reactor.py", line 38, in <module>
    from twisted.internet import default
  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/process.py", line 116, in detectLinuxBrokenPipeBehavior
    reads, writes, exes = select.select([w], [], [], 0)
exceptions.ValueError: filedescriptor out of range in select()

Failed to load application: filedescriptor out of range in select()
```

**Comment by jpmckinney** [comment]
I believe your OS is running out of file descriptors. You can increase the limit using `ulimit` (or similar, depending on your OS). See also https://stackoverflow.com/a/41497735/244258, for example.
