### ISSUE TITLE
The following error occurred when I ran spider

### ISSUE THREAD

**Issue by tsoil** [scrapy/scrapyd#294]
2018-08-31 22:27:17 [scrapy.utils.log] INFO: Scrapy 1.5.1 started (bot: blspider)
2018-08-31 22:27:17 [scrapy.utils.log] INFO: Versions: lxml 4.2.3.0, libxml2 2.9.5, cssselect 1.0.3, parsel 1.5.0, w3lib 1.19.0, Twisted 18.7.0, Python 3.5.2 (v3.5.2:4def2a2901a5, Jun 25 2016, 22:18:55) [MSC v.1900 64 bit (AMD64)], pyOpenSSL 18.0.0 (OpenSSL 1.1.0h  27 Mar 2018), cryptography 2.2.2, Platform Windows-10-10.0.10240-SP0
2018-08-31 22:27:17 [scrapy.crawler] INFO: Overridden settings: {'BOT_NAME': 'blspider', 'NEWSPIDER_MODULE': 'blspider.spiders', 'SPIDER_MODULES': ['blspider.spiders'], 'LOG_FILE': 'logs\\blspider\\jobbole\\f4f51eb0ad2911e8b4bad85de2b3d698.log'}
2018-08-31 22:27:17 [scrapy.middleware] INFO: Enabled extensions:
['scrapy.extensions.corestats.CoreStats',
 'scrapy.extensions.logstats.LogStats',
 'scrapy.extensions.telnet.TelnetConsole']
2018-08-31 22:27:17 [scrapy.middleware] INFO: Enabled downloader middlewares:
['scrapy.downloadermiddlewares.httpauth.HttpAuthMiddleware',
 'scrapy.downloadermiddlewares.downloadtimeout.DownloadTimeoutMiddleware',
 'scrapy.downloadermiddlewares.defaultheaders.DefaultHeadersMiddleware',
 'scrapy.downloadermiddlewares.useragent.UserAgentMiddleware',
 'scrapy.downloadermiddlewares.retry.RetryMiddleware',
 'scrapy.downloadermiddlewares.redirect.MetaRefreshMiddleware',
 'scrapy.downloadermiddlewares.httpcompression.HttpCompressionMiddleware',
 'scrapy.downloadermiddlewares.redirect.RedirectMiddleware',
 'scrapy.downloadermiddlewares.cookies.CookiesMiddleware',
 'scrapy.downloadermiddlewares.httpproxy.HttpProxyMiddleware',
 'scrapy.downloadermiddlewares.stats.DownloaderStats']
2018-08-31 22:27:17 [scrapy.middleware] INFO: Enabled spider middlewares:
['scrapy.spidermiddlewares.httperror.HttpErrorMiddleware',
 'scrapy.spidermiddlewares.offsite.OffsiteMiddleware',
 'scrapy.spidermiddlewares.referer.RefererMiddleware',
 'scrapy.spidermiddlewares.urllength.UrlLengthMiddleware',
 'scrapy.spidermiddlewares.depth.DepthMiddleware']
2018-08-31 22:27:17 [twisted] CRITICAL: Unhandled error in Deferred:
2018-08-31 22:27:17 [twisted] CRITICAL: 
Traceback (most recent call last):
  File "d:\git\project\allvenv\spider\lib\site-packages\twisted\internet\defer.py", line 1418, in _inlineCallbacks
    result = g.send(result)
  File "d:\git\project\allvenv\spider\lib\site-packages\scrapy\crawler.py", line 80, in crawl
    self.engine = self._create_engine()
  File "d:\git\project\allvenv\spider\lib\site-packages\scrapy\crawler.py", line 105, in _create_engine
    return ExecutionEngine(self, lambda _: self.stop())
  File "d:\git\project\allvenv\spider\lib\site-packages\scrapy\core\engine.py", line 70, in __init__
    self.scraper = Scraper(crawler)
  File "d:\git\project\allvenv\spider\lib\site-packages\scrapy\core\scraper.py", line 71, in __init__
    self.itemproc = itemproc_cls.from_crawler(crawler)
  File "d:\git\project\allvenv\spider\lib\site-packages\scrapy\middleware.py", line 58, in from_crawler
    return cls.from_settings(crawler.settings, crawler)
  File "d:\git\project\allvenv\spider\lib\site-packages\scrapy\middleware.py", line 36, in from_settings
    mw = mwcls.from_crawler(crawler)
  File "d:\git\project\allvenv\spider\lib\site-packages\scrapy\pipelines\media.py", line 68, in from_crawler
    pipe = cls.from_settings(crawler.settings)
  File "d:\git\project\allvenv\spider\lib\site-packages\scrapy\pipelines\images.py", line 98, in from_settings
    return cls(store_uri, settings=settings)
  File "d:\git\project\allvenv\spider\lib\site-packages\scrapy\pipelines\images.py", line 52, in __init__
    download_func=download_func)
  File "d:\git\project\allvenv\spider\lib\site-packages\scrapy\pipelines\files.py", line 276, in __init__
    self.store = self._get_store(store_uri)
  File "d:\git\project\allvenv\spider\lib\site-packages\scrapy\pipelines\files.py", line 315, in _get_store
    return store_cls(uri)
  File "d:\git\project\allvenv\spider\lib\site-packages\scrapy\pipelines\files.py", line 48, in __init__
    self._mkdir(self.basedir)
  File "d:\git\project\allvenv\spider\lib\site-packages\scrapy\pipelines\files.py", line 77, in _mkdir
    os.makedirs(dirname)
  File "C:\Users\dy\AppData\Local\Programs\Python\Python35\lib\os.py", line 231, in makedirs
    makedirs(head, mode, exist_ok)
  File "C:\Users\dy\AppData\Local\Programs\Python\Python35\lib\os.py", line 241, in makedirs
    mkdir(name, mode)
FileNotFoundError: [WinError 3] 系统找不到指定的路径。: 'c:\\users\\dy\\appdata\\local\\temp\\blspider-1535725609-10tnxa32.egg\\blspider'

**Comment by tsoil** [comment]
This problem has been resolved because of an incorrect directory entry during deployment
