### ISSUE TITLE
attempt to write a readonly database [BUG]

### ISSUE THREAD

**Issue by fanny** [scrapy/scrapyd#295]
When I try yo schedule a job after I have deployed a project I get the following error:
```
 Traceback (most recent call last):
  File "/usr/lib/pymodules/python2.7/scrapyd/webservice.py", line 18, in render
    return JsonResource.render(self, txrequest)
  File "/usr/local/lib/python2.7/dist-packages/scrapy/utils/txweb.py", line 10, in render
    r = resource.Resource.render(self, txrequest)
  File "/usr/local/lib/python2.7/dist-packages/twisted/web/resource.py", line 250, in render
    return m(request)
  File "/usr/lib/pymodules/python2.7/scrapyd/webservice.py", line 37, in render_POST
    self.root.scheduler.schedule(project, spider, **args)
  File "/usr/lib/pymodules/python2.7/scrapyd/scheduler.py", line 16, in schedule
    q.add(spider_name, **spider_args)
  File "/usr/lib/pymodules/python2.7/scrapyd/spiderqueue.py", line 18, in add
    self.q.put(d, priority)
  File "/usr/lib/pymodules/python2.7/scrapyd/sqlite.py", line 103, in put
    self.conn.execute(q, args)
OperationalError: attempt to write a readonly database
```

If after deploying the project I go and restart scrapyd and after schedule a job there is no problems with it and works fine. But to be honest I do not see the point of going and restarting scrapyd everytime I deploy... does not make sense.

**Comment by Digenis** [comment]
Hi @fanny,

The only thing that comes to my mind right now is the umask of the scrapyd process
but I can't think of any scenario in which the restart part would be compatible with the idea.

How do you run scrapyd and how did you install it?
(scrapyd command? init script? systemd config? docker?)

Do you have a separate user and home directory for scrapyd?

Please run the stat command against a project queue
(any file in the dbs folder, in the directory where scrapyd runs).

Also, it seems that you are using one of the 1.0.x versions.
Which one? Why?

**Comment by jpmckinney** [comment]
Closing as no response to questions for user support request.
