### ISSUE TITLE
Running scrapyd error

### ISSUE THREAD

**Issue by guoligg** [scrapy/scrapyd#310]
Python version: python3.7
Server: centos7
```
[root@localhost conf.d]# scrapyd
Unhandled Error
Traceback (most recent call last):
  File "/usr/local/python3/lib/python3.7/site-packages/twisted/application/app.py", line 674, in run
    runApp(config)
  File "/usr/local/python3/lib/python3.7/site-packages/twisted/scripts/twistd.py", line 25, in runApp
    runner.run()
  File "/usr/local/python3/lib/python3.7/site-packages/twisted/application/app.py", line 381, in run
    self.application = self.createOrGetApplication()
  File "/usr/local/python3/lib/python3.7/site-packages/twisted/application/app.py", line 453, in createOrGetApplication
    application = getApplication(self.config, passphrase)
--- <exception caught here> ---
  File "/usr/local/python3/lib/python3.7/site-packages/twisted/application/app.py", line 464, in getApplication
    application = service.loadApplication(filename, style, passphrase)
  File "/usr/local/python3/lib/python3.7/site-packages/twisted/application/service.py", line 416, in loadApplication
    application = sob.loadValueFromFile(filename, 'application')
  File "/usr/local/python3/lib/python3.7/site-packages/twisted/persisted/sob.py", line 177, in loadValueFromFile
    eval(codeObj, d, d)
  File "/usr/local/python3/lib/python3.7/site-packages/scrapyd/txapp.py", line 3, in <module>
    application = get_application()
  File "/usr/local/python3/lib/python3.7/site-packages/scrapyd/__init__.py", line 12, in get_application
    config = Config()
  File "/usr/local/python3/lib/python3.7/site-packages/scrapyd/config.py", line 21, in __init__
    self.cp.read(sources)
  File "/usr/local/python3/lib/python3.7/configparser.py", line 696, in read
    self._read(fp, filename)
  File "/usr/local/python3/lib/python3.7/configparser.py", line 1079, in _read
    raise MissingSectionHeaderError(fpname, lineno, line)
configparser.MissingSectionHeaderError: File contains no section headers.
file: 'scrapyd.conf', line: 1
'server {\n'


Failed to load application: File contains no section headers.
file: 'scrapyd.conf', line: 1
'server {\n'
```

**Comment by guoligg** [comment]
hellp ,who can help me ?my first running is ok ,stop it and restart is error,After uninstalling and reinstalling, it is still the same....

**Comment by PerrorOne** [comment]
It looks like 'scrapyd.conf' has made a mistake. It is recommended to check whether 'scrapyd.conf' is legitimate.

**Comment by guoligg** [comment]
> It looks like 'scrapyd.conf' has made a mistake. It is recommended to check whether 'scrapyd.conf' is legitimate.

thanks very much,but i think not "scrapyd,conf" wrong,maybe python3.7's env ...

**Comment by guoligg** [comment]
> It looks like 'scrapyd.conf' has made a mistake. It is recommended to check whether 'scrapyd.conf' is legitimate.
My scrapyd.conf profile is:
[scrapyd]
eggs_dir    = eggs
logs_dir    = logs
items_dir   =
jobs_to_keep = 5
dbs_dir     = dbs
max_proc    = 0
max_proc_per_cpu = 10
finished_to_keep = 100
poll_interval = 5.0
bind_address = 0.0.0.0
http_port   = 6800
debug       = off
runner      = scrapyd.runner
application = scrapyd.app.application
launcher    = scrapyd.launcher.Launcher
webroot     = scrapyd.website.Root

[services]
schedule.json     = scrapyd.webservice.Schedule
cancel.json       = scrapyd.webservice.Cancel
addversion.json   = scrapyd.webservice.AddVersion
listprojects.json = scrapyd.webservice.ListProjects
listversions.json = scrapyd.webservice.ListVersions
listspiders.json  = scrapyd.webservice.ListSpiders
delproject.json   = scrapyd.webservice.DeleteProject
delversion.json   = scrapyd.webservice.DeleteVersion
listjobs.json     = scrapyd.webservice.ListJobs
daemonstatus.json = scrapyd.webservice.DaemonStatus

**Comment by guoligg** [comment]
At the beginning of the first run, it was successful. After the process was finished, it could not be run for the second time and later.

**Comment by PerrorOne** [comment]
But the error message is displayed：'file: 'scrapyd.conf', line: 1'server {\n'', Did you check where the scrapyd directory for configuration files is? Or you can see if there is a problem with the configuration files in the following directories：

- /etc/scrapyd/scrapyd.conf (Unix)
- c:\scrapyd\scrapyd.conf (Windows)
- /etc/scrapyd/conf.d/* (in alphabetical order, Unix)
- scrapyd.conf
- ~/.scrapyd.conf (users home directory)

**Comment by Digenis** [comment]
@guoligg,
my guess is that scrapyd reads a file of yours
that you did not mean to use with scrapyd
but with some other project of yours.
Have you checked the files @PerrorOne suggests?
Does any of them start with `server: {`?
