### ISSUE TITLE
Failed to load application: dynamic module does not define module export function (PyInit__sqlite3)

### ISSUE THREAD

**Issue by 4379711** [scrapy/scrapyd#331]
```
(env) [root@instance-029wu45e scrapyd]# scrapyd
Unhandled Error
Traceback (most recent call last):
  File "/root/test/env/lib/python3.6/site-packages/Twisted-17.1.0-py3.6-linux-x86_64.egg/twisted/application/app.py", line 662, in run
    runApp(config)
  File "/root/test/env/lib/python3.6/site-packages/Twisted-17.1.0-py3.6-linux-x86_64.egg/twisted/scripts/twistd.py", line 25, in runApp
    _SomeApplicationRunner(config).run()
  File "/root/test/env/lib/python3.6/site-packages/Twisted-17.1.0-py3.6-linux-x86_64.egg/twisted/application/app.py", line 380, in run
    self.application = self.createOrGetApplication()
  File "/root/test/env/lib/python3.6/site-packages/Twisted-17.1.0-py3.6-linux-x86_64.egg/twisted/application/app.py", line 445, in createOrGetApplication
    application = getApplication(self.config, passphrase)
--- <exception caught here> ---
  File "/root/test/env/lib/python3.6/site-packages/Twisted-17.1.0-py3.6-linux-x86_64.egg/twisted/application/app.py", line 456, in getApplication
    application = service.loadApplication(filename, style, passphrase)
  File "/root/test/env/lib/python3.6/site-packages/Twisted-17.1.0-py3.6-linux-x86_64.egg/twisted/application/service.py", line 413, in loadApplication
    passphrase)
  File "/root/test/env/lib/python3.6/site-packages/Twisted-17.1.0-py3.6-linux-x86_64.egg/twisted/persisted/sob.py", line 223, in loadValueFromFile
    eval(codeObj, d, d)
  File "/root/test/env/lib/python3.6/site-packages/scrapyd-1.2.0-py3.6.egg/scrapyd/txapp.py", line 3, in <module>
    application = get_application()
  File "/root/test/env/lib/python3.6/site-packages/scrapyd-1.2.0-py3.6.egg/scrapyd/__init__.py", line 14, in get_application
    appfunc = load_object(apppath)
  File "/root/test/env/lib/python3.6/site-packages/Scrapy-1.5.2-py3.6.egg/scrapy/utils/misc.py", line 44, in load_object
    mod = import_module(module)
  File "/root/test/env/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 978, in _gcd_import
    
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load
    
  File "<frozen importlib._bootstrap>", line 950, in _find_and_load_unlocked
    
  File "<frozen importlib._bootstrap>", line 655, in _load_unlocked
    
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
    
  File "<frozen importlib._bootstrap>", line 205, in _call_with_frames_removed
    
  File "/root/test/env/lib/python3.6/site-packages/scrapyd-1.2.0-py3.6.egg/scrapyd/app.py", line 10, in <module>
    from .scheduler import SpiderScheduler
  File "/root/test/env/lib/python3.6/site-packages/scrapyd-1.2.0-py3.6.egg/scrapyd/scheduler.py", line 4, in <module>
    from .utils import get_spider_queues
  File "/root/test/env/lib/python3.6/site-packages/scrapyd-1.2.0-py3.6.egg/scrapyd/utils.py", line 3, in <module>
    from .sqlite import JsonSqliteDict
  File "/root/test/env/lib/python3.6/site-packages/scrapyd-1.2.0-py3.6.egg/scrapyd/sqlite.py", line 1, in <module>
    import sqlite3
  File "/usr/local/lib/python3.6/sqlite3/__init__.py", line 23, in <module>
    from sqlite3.dbapi2 import *
  File "/usr/local/lib/python3.6/sqlite3/dbapi2.py", line 27, in <module>
    from _sqlite3 import *
builtins.ImportError: dynamic module does not define module export function (PyInit__sqlite3)


Failed to load application: dynamic module does not define module export function (PyInit__sqlite3)
```

**Comment by Digenis** [comment]
I see you have python installed in your /usr/local/ so my guess is that you compiled it yourself.
Refer to your system manual for installing python, or libraries in general.
There are mailing lists and sites such as stackoverflow to ask for help.

Feel free to reopen this issue if you believe it's a scrapyd bug.
