### ISSUE TITLE
start scrapyd error

### ISSUE THREAD

**Issue by xudun** [scrapy/scrapyd#333]
Unhandled Error
Traceback (most recent call last):
  File "/usr/local/python3/lib/python3.7/site-packages/Twisted-19.2.0-py3.7-linux-x86_64.egg/twisted/application/app.py", line 674, in run
    runApp(config)
  File "/usr/local/python3/lib/python3.7/site-packages/Twisted-19.2.0-py3.7-linux-x86_64.egg/twisted/scripts/twistd.py", line 25, in runApp
    runner.run()
  File "/usr/local/python3/lib/python3.7/site-packages/Twisted-19.2.0-py3.7-linux-x86_64.egg/twisted/application/app.py", line 381, in run
    self.application = self.createOrGetApplication()
  File "/usr/local/python3/lib/python3.7/site-packages/Twisted-19.2.0-py3.7-linux-x86_64.egg/twisted/application/app.py", line 453, in createOrGetApplication
    application = getApplication(self.config, passphrase)
--- <exception caught here> ---
  File "/usr/local/python3/lib/python3.7/site-packages/Twisted-19.2.0-py3.7-linux-x86_64.egg/twisted/application/app.py", line 464, in getApplication
    application = service.loadApplication(filename, style, passphrase)
  File "/usr/local/python3/lib/python3.7/site-packages/Twisted-19.2.0-py3.7-linux-x86_64.egg/twisted/application/service.py", line 416, in loadApplication
    application = sob.loadValueFromFile(filename, 'application')
  File "/usr/local/python3/lib/python3.7/site-packages/Twisted-19.2.0-py3.7-linux-x86_64.egg/twisted/persisted/sob.py", line 177, in loadValueFromFile
    eval(codeObj, d, d)
  File "/usr/local/python3/lib/python3.7/site-packages/scrapyd/txapp.py", line 3, in <module>
    application = get_application()
  File "/usr/local/python3/lib/python3.7/site-packages/scrapyd/__init__.py", line 15, in get_application
    return appfunc(config)
  File "/usr/local/python3/lib/python3.7/site-packages/scrapyd/app.py", line 39, in application
    webservice = TCPServer(http_port, server.Site(webcls(config, app)), interface=bind_address)
  File "/usr/local/python3/lib/python3.7/site-packages/scrapyd/website.py", line 33, in __init__
    servCls = load_object(servClsName)
  File "/usr/local/python3/lib/python3.7/site-packages/scrapy/utils/misc.py", line 49, in load_object
    raise NameError("Module '%s' doesn't define any object named '%s'" % (module, name))
builtins.NameError: Module 'scrapyd.webservice' doesn't define any object named 'DaemonStatu'

**Comment by my8100** [comment]
```
builtins.NameError: Module 'scrapyd.webservice' doesn't define any object named 'DaemonStatu'
```
Maybe you should check out [the config file of Scrapyd](https://scrapyd.readthedocs.io/en/latest/config.html)
and change `DaemonStatu` to `DaemonStatus`.
```
daemonstatus.json = scrapyd.webservice.DaemonStatus
```

**Comment by my8100** [comment]
BTW, run `pip install -U Twisted==18.9.0` if Scrapyd was installed via pip, see #311.

**Comment by xudun** [comment]
@my8100 it worked,thanks for your help!
