### ISSUE TITLE
Arguments contain a non-string value

### ISSUE THREAD

**Issue by iml885203** [scrapy/scrapyd#353]
I would like to use the curl command with utf-8 parameters like this :

```
curl http://localhost:6800/schedule.json -d project=example -d spider=myspider -d arg1=測試
```

And I get some error message `Arguments contain a non-string value`:

![螢幕快照 2019-08-20 下午5 45 18](https://user-images.githubusercontent.com/17023091/63337173-14da0a80-c373-11e9-9c47-0962e6435ff1.png)

**Comment by my8100** [comment]
Can you run the command below and post the result?
```
python -c "import scrapyd; import twisted; print(scrapyd.__version__, twisted.__version__)"
```

**Comment by iml885203** [comment]
> Can you run the command below and post the result?
> 
> ```
> python -c "import scrapyd; import twisted; print(scrapyd.__version__, twisted.__version__)"
> ```

![螢幕快照 2019-08-20 下午6 08 47](https://user-images.githubusercontent.com/17023091/63338542-959a0600-c375-11e9-8b4e-7690c23eb1e9.png)

**Comment by my8100** [comment]
I cannot reproduce the problem.
What's the version of your curl?
Can you restart Scrapyd and schedule the job again?

```
(py3) $ scrapyd
2019-08-20T18:22:36+0800 [twisted.scripts._twistd_unix.UnixAppLogger#info] twistd 19.7.0 (/home/py3/bin/python3.6 3.6.5) starting up.
2019-08-20T18:22:36+0800 [Launcher] Scrapyd 1.2.1 started: max_proc=4, runner='scrapyd.runner'
```
```
$ curl --version
curl 7.29.0
$ curl http://localhost:18600/schedule.json -d project=demo -d spider=test -d arg1=測試
{"node_name": "hostname", "status": "ok", "jobid": "a4bac070c33411e99dc100163e0e9e50"}
```
```
2019-08-20 18:24:13 [test] DEBUG: self.arg1: 測試
```

**Comment by iml885203** [comment]
my curl version
```
$ curl --version
curl 7.47.0
```

----

I try this issue again

**Comment by iml885203** [comment]
my curl version
```
$ curl --version
curl 7.47.0
```

----

I try this issue again

**Spider**
```python
import scrapy
import logging

class NonstringSpider(scrapy.Spider):
    name = 'nonstring'
    allowed_domains = ['example.com']
    start_urls = ['http://example.com/']

    # import args
    def __init__(self, category=None, *args, **kwargs):
        super(NonstringSpider, self).__init__(*args, **kwargs)

    def parse(self, response):
        logging.debug(f"self.arg1: {self.arg1}")
```

**It can run in commands**
```
$ scrapy crawl nonstring -a arg1=測試
```
```
2019-08-21 04:37:15 [root] DEBUG: self.arg1: 測試
```

**but get error when run in scrpayd**
```
$ curl http://192.168.33.82:6800/schedule.json -d project=issue_example -d spider=nonstring -d arg1=測試
{"node_name": "b89dfb70345a", "status": "ok", "jobid": "88feecbec3cd11e9b8cc0242ac120006"}
```

error in scrapyd logs
```
2019-08-21T04:38:34+0000 [twisted.python.log#info] "192.168.33.82" - - [21/Aug/2019:04:38:32 +0000] "POST /schedule.json HTTP/1.1" 200 91 "-" "curl/7.47.0"
2019-08-21T04:38:37+0000 [twisted.internet.defer#critical] Unhandled error in Deferred:
2019-08-21T04:38:37+0000 [twisted.internet.defer#critical]
	Traceback (most recent call last):
	  File "/var/lnb-scrapyd/venv/lib/python3.6/site-packages/scrapyd/poller.py", line 25, in poll
	    returnValue(self.dq.put(self._message(msg, p)))
	  File "/var/lnb-scrapyd/venv/lib/python3.6/site-packages/twisted/internet/defer.py", line 1872, in put
	    self.waiting.pop(0).callback(obj)
	  File "/var/lnb-scrapyd/venv/lib/python3.6/site-packages/twisted/internet/defer.py", line 460, in callback
	    self._startRunCallbacks(result)
	  File "/var/lnb-scrapyd/venv/lib/python3.6/site-packages/twisted/internet/defer.py", line 568, in _startRunCallbacks
	    self._runCallbacks()
	--- <exception caught here> ---
	  File "/var/lnb-scrapyd/venv/lib/python3.6/site-packages/twisted/internet/defer.py", line 654, in _runCallbacks
	    current.result = callback(current.result, *args, **kw)
	  File "/var/lnb-scrapyd/venv/lib/python3.6/site-packages/scrapyd/launcher.py", line 47, in _spawn_process
	    reactor.spawnProcess(pp, sys.executable, args=args, env=env)
	  File "/var/lnb-scrapyd/venv/lib/python3.6/site-packages/twisted/internet/posixbase.py", line 331, in spawnProcess
	    args, env = self._checkProcessArgs(args, env)
	  File "/var/lnb-scrapyd/venv/lib/python3.6/site-packages/twisted/internet/base.py", line 992, in _checkProcessArgs
	    raise TypeError("Arguments contain a non-string value")
	builtins.TypeError: Arguments contain a non-string value
```

**Comment by my8100** [comment]
Modify the code below in file */var/lnb-scrapyd/venv/lib/python3.6/site-packages/twisted/internet/base.py*, then restart Scrapyd, try again and post the log of Scrapyd.

https://github.com/twisted/twisted/blob/trunk/src/twisted/internet/base.py#L989-L990
```
        print(defaultEncoding)
        for arg in args:
            print(arg)
            arg = argChecker(arg)
```

**Comment by iml885203** [comment]
@my8100 thank you!

I solved this problem myself. haha

it's my system encode problem in docker

twisted will encode arg by default encoding
https://github.com/twisted/twisted/blob/trunk/src/twisted/internet/base.py#L963-L994

so I check my default encoding
```
$ python -c "import sys;print(sys.getfilesystemencoding())"
ascii
```

and run this command to solve
```
LANG=C.UTF-8 bash
$ python -c "import sys;print(sys.getfilesystemencoding())"
utf-8
```
