### ISSUE TITLE
Failed to load application: cannot import name 'get_application' from 'scrapyd' 

### ISSUE THREAD

**Issue by allran** [scrapy/scrapyd#357]
```
(VideoManage) ➜  video_scrapy git:(master) ✗ scrapyd
Unhandled Error
Traceback (most recent call last):
  File "/Users/allran/.virtualenv/VideoManage/lib/python3.7/site-packages/twisted/application/app.py", line 674, in run
    runApp(config)
  File "/Users/allran/.virtualenv/VideoManage/lib/python3.7/site-packages/twisted/scripts/twistd.py", line 25, in runApp
    runner.run()
  File "/Users/allran/.virtualenv/VideoManage/lib/python3.7/site-packages/twisted/application/app.py", line 381, in run
    self.application = self.createOrGetApplication()
  File "/Users/allran/.virtualenv/VideoManage/lib/python3.7/site-packages/twisted/application/app.py", line 453, in createOrGetApplication
    application = getApplication(self.config, passphrase)
--- <exception caught here> ---
  File "/Users/allran/.virtualenv/VideoManage/lib/python3.7/site-packages/twisted/application/app.py", line 464, in getApplication
    application = service.loadApplication(filename, style, passphrase)
  File "/Users/allran/.virtualenv/VideoManage/lib/python3.7/site-packages/twisted/application/service.py", line 416, in loadApplication
    application = sob.loadValueFromFile(filename, 'application')
  File "/Users/allran/.virtualenv/VideoManage/lib/python3.7/site-packages/twisted/persisted/sob.py", line 177, in loadValueFromFile
    eval(codeObj, d, d)
  File "/Users/allran/.virtualenv/VideoManage/lib/python3.7/site-packages/scrapyd/txapp.py", line 2, in <module>
    from scrapyd import get_application
builtins.ImportError: cannot import name 'get_application' from 'scrapyd' (/Users/allran/.virtualenv/VideoManage/lib/python3.7/site-packages/scrapyd/__init__.py)


Failed to load application: cannot import name 'get_application' from 'scrapyd' (/Users/allran/.virtualenv/VideoManage/lib/python3.7/site-packages/scrapyd/__init__.py)
```

**Comment by Lofoer** [comment]
+1

**Comment by my8100** [comment]
For comparison, can you new a virtual env and install Scrapyd solely?
If still fail, please post the result of command “pip list” in the new virtual env?

**Comment by jpmckinney** [comment]
Cannot reproduce, and no answer to the question in over a year.
