### ISSUE TITLE
api listjobs.json KeyError: 'project'

### ISSUE THREAD

**Issue by Apuyuseng** [scrapy/scrapyd#358]
run cmd
```
$ curl http://localhost:6800/listjobs.json
{"node_name": "apudeMacBook-Pro.local", "status": "error", "message": "'project'"}
``` 

get log
```log
2019-11-08T01:22:41+0800 [_GenericHTTPChannelProtocol,2,127.0.0.1] Unhandled Error
	Traceback (most recent call last):
	  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/twisted/web/http.py", line 2237, in allContentReceived
	    req.requestReceived(command, path, version)
	  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/twisted/web/http.py", line 937, in requestReceived
	    self.process()
	  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/twisted/web/server.py", line 217, in process
	    self.render(resrc)
	  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/twisted/web/server.py", line 284, in render
	    body = resrc.render(self)
	--- <exception caught here> ---
	  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/scrapyd/webservice.py", line 21, in render
	    return JsonResource.render(self, txrequest).encode('utf-8')
	  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/scrapyd/utils.py", line 20, in render
	    r = resource.Resource.render(self, txrequest)
	  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/twisted/web/resource.py", line 265, in render
	    return m(request)
	  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/scrapyd/webservice.py", line 120, in render_GET
	    project = args['project'][0]
	builtins.KeyError: 'project'
	
2019-11-08T01:22:41+0800 [twisted.python.log#info] "127.0.0.1" - - [07/Nov/2019:17:22:40 +0000] "GET /listjobs.json HTTP/1.1" 200 83 "-" "python-requests/2.22.0"
```

**Comment by Apuyuseng** [comment]
solve 
```cmd
$ pip3 install git+https://github.com/scrapy/scrapyd.git
```
