### ISSUE TITLE
scrapyd poll error

### ISSUE THREAD

**Issue by insanemainframe** [scrapy/scrapyd#6]
```python
2013-02-26 16:02:56+0100 [-] Unhandled Error
        Traceback (most recent call last):
          File "/home/innuendo/.virtualenvs/nazya/local/lib/python2.7/site-packages/twisted/internet/base.py", line 805, in runUntilCurrent
            call.func(*call.args, **call.kw)
          File "/home/innuendo/.virtualenvs/nazya/local/lib/python2.7/site-packages/twisted/internet/task.py", line 218, in __call__
            d = defer.maybeDeferred(self.f, *self.a, **self.kw)
          File "/home/innuendo/.virtualenvs/nazya/local/lib/python2.7/site-packages/twisted/internet/defer.py", line 138, in maybeDeferred
            result = f(*args, **kw)
          File "/home/innuendo/.virtualenvs/nazya/local/lib/python2.7/site-packages/twisted/internet/defer.py", line 1214, in unwindGenerator
            return _inlineCallbacks(None, gen, Deferred())
        --- <exception caught here> ---
          File "/home/innuendo/.virtualenvs/nazya/local/lib/python2.7/site-packages/twisted/internet/defer.py", line 1071, in _inlineCallbacks
            result = g.send(result)
          File "/home/innuendo/.virtualenvs/nazya/local/lib/python2.7/site-packages/scrapyd/poller.py", line 24, in poll
            returnValue(self.dq.put(self._message(msg, p)))
          File "/home/innuendo/.virtualenvs/nazya/local/lib/python2.7/site-packages/scrapyd/poller.py", line 33, in _message
            d = queue_msg.copy()
        exceptions.AttributeError: 'NoneType' object has no attribute 'copy'
```

**Comment by Digenis** [comment]
This is #40 and https://github.com/scrapy/scrapy/issues/28

**Comment by Digenis** [comment]
Closing in favour of #40.
