### ISSUE TITLE
scrapyd on windows failes to accept API requests

### ISSUE THREAD

**Issue by rotemblu** [scrapy/scrapyd#68]
I use scrapyd on windows, I successfully installed it, but when I try to use the API I get an error that is related to the environment variables:
it happens in addversion call: 

```
2014-11-12 17:52:54+0200 [HTTPChannel,4,127.0.0.1] 127.0.0.1 - - [12/Nov/2014:15:52:52 +0000] "POST /addversion.json HTT
P/1.1" 200 115 "-" "Python-urllib/2.7"
2014-11-12 17:54:41+0200 [HTTPChannel,5,10.10.1.203] Unhandled Error
        Traceback (most recent call last):
          File "C:\Python27\lib\site-packages\twisted\web\http.py", line 1618, in allContentReceived
            req.requestReceived(command, path, version)
          File "C:\Python27\lib\site-packages\twisted\web\http.py", line 773, in requestReceived
            self.process()
          File "C:\Python27\lib\site-packages\twisted\web\server.py", line 132, in process
            self.render(resrc)
          File "C:\Python27\lib\site-packages\twisted\web\server.py", line 167, in render
            body = resrc.render(self)
        --- <exception caught here> ---
          File "C:\Python27\lib\site-packages\scrapyd-1.0.1-py2.7.egg\scrapyd\webservice.py", line 17, in render
            return JsonResource.render(self, txrequest)
          File "C:\Python27\lib\site-packages\scrapyd-1.0.1-py2.7.egg\scrapyd\utils.py", line 19, in render
            r = resource.Resource.render(self, txrequest)
          File "C:\Python27\lib\site-packages\twisted\web\resource.py", line 216, in render
            return m(request)
          File "C:\Python27\lib\site-packages\scrapyd-1.0.1-py2.7.egg\scrapyd\webservice.py", line 33, in render_POST
            spiders = get_spider_list(project)
          File "C:\Python27\lib\site-packages\scrapyd-1.0.1-py2.7.egg\scrapyd\utils.py", line 114, in get_spider_list
            raise RuntimeError(msg.splitlines()[-1])
        exceptions.RuntimeError: Use "scrapy" to see available commands
```

it happens also in schedule call(same error).

looking at the file https://github.com/scrapy/scrapyd/blob/master/scrapyd/utils.py
I see this is related to the following lines of code:

``` python
env = os.environ.copy()
    env['SCRAPY_PROJECT'] = project
    if pythonpath:
        env['PYTHONPATH'] = pythonpath
    pargs = [sys.executable, '-m', runner, 'list']
    proc = Popen(pargs, stdout=PIPE, stderr=PIPE, env=env)
    out, err = proc.communicate()
    if proc.returncode:
        msg = err or out or 'unknown error'
        raise RuntimeError(msg.splitlines()[-1])
```

which means something in the connection with windows environment throws error.
I really appreciate any help.

**Comment by hanlulong** [comment]
Hi. I had exactly the same problem. It turned out I did not execute the scrapyd command under my project folder. The error is actually indicating scrapyd cannot find a useable scrapy command/project setting.

The solution is simply to run scrapyd under your project folder (with the virtual environment).

**Comment by Digenis** [comment]
This is not a correct solution.
scrapyd shouldn't be in a project folder at all,
it should find modules using PYTHONPATH,
not the working directory.
It's meant to handle multiple projects.

Currently, scrapyd doesn't support windows.
We need a contributor with the means to implement and test it.

**Comment by Digenis** [comment]
closing due to lack of activity and old scrapyd version
